-- One-time data fix, APPLIED 2026-09-29 on staging (pre-2026-08-31 replayed-legacy gold history).
-- Policy "no clamps distorting data": a factor stored as exactly 1.0 while the row's own
-- components say more (P = gross·available/(ideal·running), OEE = net/ideal) was a cap.
--   1. Replace ONLY those capped values with the component value (75,729 rows across 8 tables;
--      every other row untouched → legacy-parity rows stay byte-identical). Old values are
--      snapshotted in ops._bkp_history_uncap_20260929 (tbl, key_id, ts_value, oee, oee_p).
--   2. Values above 10 are impossible (tiny running times, replay artifacts): NULL (= no
--      reading, which the UI already renders as not metered) + an OEE_GT_1 data_quality_event
--      for the equipment grains (2,193 events). 1.0 was never true for these either.
-- Q was never capped visibly in history (legacy never stored net > gross).
-- shift_weekly/shift_monthly store no components → untouched.
BEGIN;
SET LOCAL statement_timeout = '20min';
CREATE TABLE ops._bkp_history_uncap_20260929 (tbl text, key_id int, ts_value timestamptz, oee float8, oee_p float8);
INSERT INTO ops._bkp_history_uncap_20260929 SELECT 'equipment_oee_hourly', id_equipment, ts_value::timestamptz, oee, oee_p FROM gold.equipment_oee_hourly WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
UPDATE gold.equipment_oee_hourly SET oee_p = CASE WHEN oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time THEN gross::float8*available_time/(ideal_production*running_time) ELSE oee_p END, oee = CASE WHEN oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production THEN net::float8/ideal_production ELSE oee END WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
INSERT INTO ops._bkp_history_uncap_20260929 SELECT 'equipment_oee_shift', id_equipment, ts_value::timestamptz, oee, oee_p FROM gold.equipment_oee_shift WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
UPDATE gold.equipment_oee_shift SET oee_p = CASE WHEN oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time THEN gross::float8*available_time/(ideal_production*running_time) ELSE oee_p END, oee = CASE WHEN oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production THEN net::float8/ideal_production ELSE oee END WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
INSERT INTO ops._bkp_history_uncap_20260929 SELECT 'equipment_oee_daily', id_equipment, ts_value::timestamptz, oee, oee_p FROM gold.equipment_oee_daily WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
UPDATE gold.equipment_oee_daily SET oee_p = CASE WHEN oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time THEN gross::float8*available_time/(ideal_production*running_time) ELSE oee_p END, oee = CASE WHEN oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production THEN net::float8/ideal_production ELSE oee END WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
INSERT INTO ops._bkp_history_uncap_20260929 SELECT 'equipment_oee_weekly', id_equipment, ts_value::timestamptz, oee, oee_p FROM gold.equipment_oee_weekly WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
UPDATE gold.equipment_oee_weekly SET oee_p = CASE WHEN oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time THEN gross::float8*available_time/(ideal_production*running_time) ELSE oee_p END, oee = CASE WHEN oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production THEN net::float8/ideal_production ELSE oee END WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
INSERT INTO ops._bkp_history_uncap_20260929 SELECT 'equipment_oee_monthly', id_equipment, ts_value::timestamptz, oee, oee_p FROM gold.equipment_oee_monthly WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
UPDATE gold.equipment_oee_monthly SET oee_p = CASE WHEN oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time THEN gross::float8*available_time/(ideal_production*running_time) ELSE oee_p END, oee = CASE WHEN oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production THEN net::float8/ideal_production ELSE oee END WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
INSERT INTO ops._bkp_history_uncap_20260929 SELECT 'area_oee_shift', id_area, ts_value::timestamptz, oee, oee_p FROM gold.area_oee_shift WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
UPDATE gold.area_oee_shift SET oee_p = CASE WHEN oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time THEN gross::float8*available_time/(ideal_production*running_time) ELSE oee_p END, oee = CASE WHEN oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production THEN net::float8/ideal_production ELSE oee END WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
INSERT INTO ops._bkp_history_uncap_20260929 SELECT 'site_oee_shift', id_site, ts_value::timestamptz, oee, oee_p FROM gold.site_oee_shift WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
UPDATE gold.site_oee_shift SET oee_p = CASE WHEN oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time THEN gross::float8*available_time/(ideal_production*running_time) ELSE oee_p END, oee = CASE WHEN oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production THEN net::float8/ideal_production ELSE oee END WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
INSERT INTO ops._bkp_history_uncap_20260929 SELECT 'area_oee_daily', id_area, ts_value::timestamptz, oee, oee_p FROM gold.area_oee_daily WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
UPDATE gold.area_oee_daily SET oee_p = CASE WHEN oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time THEN gross::float8*available_time/(ideal_production*running_time) ELSE oee_p END, oee = CASE WHEN oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production THEN net::float8/ideal_production ELSE oee END WHERE ts_value < '2026-08-31' AND ((oee_p = 1 AND running_time>0 AND ideal_production>0 AND gross*available_time > 1.0001*ideal_production*running_time) OR (oee = 1 AND ideal_production>0 AND net > 1.0001*ideal_production));
SELECT 'snapshot', tbl, count(*) FROM ops._bkp_history_uncap_20260929 GROUP BY 1,2 ORDER BY 2;
COMMIT;
BEGIN;
SET LOCAL statement_timeout = '20min';
INSERT INTO silver.data_quality_event (id_enterprise, id_equipment, grain, bucket_ts, rule, observed_value, severity) SELECT q.id_enterprise, e.id_equipment, 'hour', e.ts_value::timestamptz, 'OEE_GT_1', greatest(e.oee, e.oee_p), 'error' FROM gold.equipment_oee_hourly e JOIN core.equipments q USING (id_equipment) WHERE e.ts_value < '2026-08-31' AND (e.oee_p > 10 OR e.oee > 10) ON CONFLICT (id_enterprise, COALESCE(id_equipment, 0), grain, bucket_ts, rule) DO UPDATE SET observed_value = EXCLUDED.observed_value, detected_at = now();
INSERT INTO silver.data_quality_event (id_enterprise, id_equipment, grain, bucket_ts, rule, observed_value, severity) SELECT q.id_enterprise, e.id_equipment, 'shift', e.ts_value::timestamptz, 'OEE_GT_1', greatest(e.oee, e.oee_p), 'error' FROM gold.equipment_oee_shift e JOIN core.equipments q USING (id_equipment) WHERE e.ts_value < '2026-08-31' AND (e.oee_p > 10 OR e.oee > 10) ON CONFLICT (id_enterprise, COALESCE(id_equipment, 0), grain, bucket_ts, rule) DO UPDATE SET observed_value = EXCLUDED.observed_value, detected_at = now();
INSERT INTO silver.data_quality_event (id_enterprise, id_equipment, grain, bucket_ts, rule, observed_value, severity) SELECT q.id_enterprise, e.id_equipment, 'day', e.ts_value::timestamptz, 'OEE_GT_1', greatest(e.oee, e.oee_p), 'error' FROM gold.equipment_oee_daily e JOIN core.equipments q USING (id_equipment) WHERE e.ts_value < '2026-08-31' AND (e.oee_p > 10 OR e.oee > 10) ON CONFLICT (id_enterprise, COALESCE(id_equipment, 0), grain, bucket_ts, rule) DO UPDATE SET observed_value = EXCLUDED.observed_value, detected_at = now();
INSERT INTO silver.data_quality_event (id_enterprise, id_equipment, grain, bucket_ts, rule, observed_value, severity) SELECT q.id_enterprise, e.id_equipment, 'week', e.ts_value::timestamptz, 'OEE_GT_1', greatest(e.oee, e.oee_p), 'error' FROM gold.equipment_oee_weekly e JOIN core.equipments q USING (id_equipment) WHERE e.ts_value < '2026-08-31' AND (e.oee_p > 10 OR e.oee > 10) ON CONFLICT (id_enterprise, COALESCE(id_equipment, 0), grain, bucket_ts, rule) DO UPDATE SET observed_value = EXCLUDED.observed_value, detected_at = now();
INSERT INTO silver.data_quality_event (id_enterprise, id_equipment, grain, bucket_ts, rule, observed_value, severity) SELECT q.id_enterprise, e.id_equipment, 'month', e.ts_value::timestamptz, 'OEE_GT_1', greatest(e.oee, e.oee_p), 'error' FROM gold.equipment_oee_monthly e JOIN core.equipments q USING (id_equipment) WHERE e.ts_value < '2026-08-31' AND (e.oee_p > 10 OR e.oee > 10) ON CONFLICT (id_enterprise, COALESCE(id_equipment, 0), grain, bucket_ts, rule) DO UPDATE SET observed_value = EXCLUDED.observed_value, detected_at = now();
UPDATE gold.equipment_oee_hourly SET oee_p = CASE WHEN oee_p > 10 THEN NULL ELSE oee_p END, oee = CASE WHEN oee > 10 THEN NULL ELSE oee END WHERE ts_value < '2026-08-31' AND (oee_p > 10 OR oee > 10);
UPDATE gold.equipment_oee_shift SET oee_p = CASE WHEN oee_p > 10 THEN NULL ELSE oee_p END, oee = CASE WHEN oee > 10 THEN NULL ELSE oee END WHERE ts_value < '2026-08-31' AND (oee_p > 10 OR oee > 10);
UPDATE gold.equipment_oee_daily SET oee_p = CASE WHEN oee_p > 10 THEN NULL ELSE oee_p END, oee = CASE WHEN oee > 10 THEN NULL ELSE oee END WHERE ts_value < '2026-08-31' AND (oee_p > 10 OR oee > 10);
UPDATE gold.equipment_oee_weekly SET oee_p = CASE WHEN oee_p > 10 THEN NULL ELSE oee_p END, oee = CASE WHEN oee > 10 THEN NULL ELSE oee END WHERE ts_value < '2026-08-31' AND (oee_p > 10 OR oee > 10);
UPDATE gold.equipment_oee_monthly SET oee_p = CASE WHEN oee_p > 10 THEN NULL ELSE oee_p END, oee = CASE WHEN oee > 10 THEN NULL ELSE oee END WHERE ts_value < '2026-08-31' AND (oee_p > 10 OR oee > 10);
UPDATE gold.area_oee_shift SET oee_p = CASE WHEN oee_p > 10 THEN NULL ELSE oee_p END, oee = CASE WHEN oee > 10 THEN NULL ELSE oee END WHERE ts_value < '2026-08-31' AND (oee_p > 10 OR oee > 10);
UPDATE gold.site_oee_shift SET oee_p = CASE WHEN oee_p > 10 THEN NULL ELSE oee_p END, oee = CASE WHEN oee > 10 THEN NULL ELSE oee END WHERE ts_value < '2026-08-31' AND (oee_p > 10 OR oee > 10);
UPDATE gold.area_oee_daily SET oee_p = CASE WHEN oee_p > 10 THEN NULL ELSE oee_p END, oee = CASE WHEN oee > 10 THEN NULL ELSE oee END WHERE ts_value < '2026-08-31' AND (oee_p > 10 OR oee > 10);
COMMIT;
