#!/usr/bin/env bash
# Populate e2e/.env from AWS Secrets Manager (packiot/staging/e2e-test-creds).
# The secret is the scalable per-client source of truth; this flattens it into
# the flat KEY=value shape playwright.config.ts + the specs read via dotenv.
# Requires: aws CLI creds with secretsmanager:GetSecretValue, jq.
set -euo pipefail
SECRET="${E2E_CREDS_SECRET:-packiot/staging/e2e-test-creds}"
REGION="${AWS_REGION:-us-east-1}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/.env"

json="$(aws secretsmanager get-secret-value --secret-id "$SECRET" --region "$REGION" --query SecretString --output text)"

{
  echo "# Generated by scripts/fetch-creds.sh from $SECRET — do not commit."
  echo "$json" | jq -r '.urls | to_entries[] | "\(.key|ascii_upcase)_URL=\(.value)"'
  # cpack client → front4 + operator + the CPACK_* data test
  echo "$json" | jq -r '
    .clients.cpack as $c |
    "FRONT4_USER=\($c.user)","FRONT4_PASSWORD=\($c.password)",
    "CPACK_USER=\($c.user)","CPACK_PASSWORD=\($c.password)","CPACK_ENTERPRISE_ID=\($c.enterpriseId)",
    "OPERATOR_USER=\($c.user)","OPERATOR_PASSWORD=\($c.password)"'
  # platform csadmin → csadmin + customize consoles
  echo "$json" | jq -r '
    .platform.csadmin as $p |
    "CSADMIN_USER=\($p.user)","CSADMIN_PASSWORD=\($p.password)",
    "CUSTOMIZE_USER=\($p.user)","CUSTOMIZE_PASSWORD=\($p.password)"'
  # sandbox twin (ent 2000003) → operator-sbx MUTATING journeys (self-healing playground)
  echo "$json" | jq -r '
    .clients.sandbox as $s |
    "OPERATOR_SBX_URL=\($s.operatorUrl)",
    "SANDBOX_USER=\($s.user)","SANDBOX_PASSWORD=\($s.password)","SANDBOX_ENTERPRISE_ID=\($s.enterpriseId)"'
} > "$OUT"
echo "wrote $OUT ($(grep -c = "$OUT") vars) from $SECRET"
