slice_name: Disponibilidade
description: bi.oee_shift AVG(oee_a). front4 OeeScore Availability column.
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 6__table
  viz_type: big_number_total
  metric: avg_oee_a
  adhoc_filters: []
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: .1%
  subtitle: Availability
  annotation_layers: []
  granularity_sqla: ts_value
  time_range: 'DATEADD(DATETIME(''now''), -1, day) : now'
query_context: '{"datasource": {"id": 6, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "columns": [], "metrics": ["avg_oee_a"], "annotation_layers": [], "series_limit":
  0, "order_desc": true, "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "granularity": "ts_value", "time_range": "DATEADD(DATETIME(''now''), -1, day)
  : now"}], "form_data": {"datasource": "6__table", "viz_type": "big_number_total",
  "metric": "avg_oee_a", "adhoc_filters": [], "header_font_size": 0.4, "subheader_font_size":
  0.15, "y_axis_format": ".1%", "subtitle": "Availability", "annotation_layers": [],
  "slice_id": 1, "force": false, "result_format": "json", "result_type": "full", "granularity_sqla":
  "ts_value", "time_range": "DATEADD(DATETIME(''now''), -1, day) : now"}, "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: 9232e211-3d11-42bb-bcf4-3a8f394cc2c9
version: 1.0.0
dataset_uuid: 1546df03-4e11-40b8-94d7-aa149b12c58a
