# front4 shiftOee Performance leg (oee_p). Big Number, % format.
slice_name: Performance
description: bi.oee_shift AVG(oee_p). front4 OeeScore Performance column.
certified_by: null
certification_details: null
viz_type: big_number_total
params: |
  {
    "datasource": "1546df03-4e11-40b8-94d7-aa149b12c58a__table",
    "viz_type": "big_number_total",
    "metric": "avg_oee_p",
    "adhoc_filters": [],
    "header_font_size": 0.4,
    "subheader_font_size": 0.15,
    "y_axis_format": ".1%",
    "subtitle": "Performance"
  }
query_context: null
cache_timeout: null
uuid: b6f6e3fd-cc9b-4131-8d7a-4ea89968f2f8
version: 1.0.0
dataset_uuid: 1546df03-4e11-40b8-94d7-aa149b12c58a
