package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/packiot/packiot-stack-alpha/services/shadow-mirror/internal/replay"
)

// OrderChangedPayload — user_logs.category='order-changed'. Combined
// action that closes the OLD PO and optionally creates a NEW one in
// one atomic operator step.
//
// Real sampled payload (2026-07-01 staging):
//   {"idArea":3,"idSite":3,"idOrder":1782926737,"stopType":"finish",
//    "timestamp":"...","idEquipment":5,"idEnterprise":2,
//    "shouldCreatePo":true,"shouldOpenNewPo":true,
//    "idProductionOrder":null,"oldIdProductionOrder":17465,
//    "productionOrderQuantity":4206,"oldProductionOrderProdFinal":0}
//
// Note: idProductionOrder is NULL in the payload — the NEW PO's id
// is generated by edge-api at write time. shadow-mirror can't
// deterministically reproduce that id, so:
//   - Step 1 (always): UPDATE the old PO by oldIdProductionOrder
//   - Step 2 (if shouldCreatePo=true): INSERT a new PO keyed by
//     (id_order, id_equipment) with ON CONFLICT DO NOTHING —
//     shadow paths generate their own id_production_order via the
//     PK sequence, so subsequent updates by id_production_order
//     WON'T match on shadow. This is the "id coordination complexity"
//     flagged in task #83. Acceptable for POC parity of Flow 1 vs
//     Flow 2/3 aggregate stats; not for exact-id lookups.
type OrderChangedPayload struct {
	IDArea                      int    `json:"idArea"`
	IDSite                      int    `json:"idSite"`
	IDOrder                     int64  `json:"idOrder"`
	StopType                    string `json:"stopType"`  // "finish" | "pause"
	Timestamp                   string `json:"timestamp"` // ISO-8601 UTC
	IDEquipment                 int    `json:"idEquipment"`
	IDEnterprise                int    `json:"idEnterprise"`
	ShouldCreatePo              bool   `json:"shouldCreatePo"`
	ShouldOpenNewPo             bool   `json:"shouldOpenNewPo"`
	OldIDProductionOrder        int64  `json:"oldIdProductionOrder"`
	ProductionOrderQuantity     int64  `json:"productionOrderQuantity"`
	OldProductionOrderProdFinal int64  `json:"oldProductionOrderProdFinal"`
}

// OrderChanged closes the old PO and (optionally) inserts a new one.
// Both operations replay against each shadow path.
func OrderChanged(logger *slog.Logger) replay.Handler {
	return func(ctx context.Context, mainPool, shadowPool *pgxpool.Pool, u *replay.UserLog) error {
		var p OrderChangedPayload
		if err := json.Unmarshal(u.Payload, &p); err != nil {
			return replay.ErrSkip
		}
		if p.OldIDProductionOrder == 0 {
			return replay.ErrSkip
		}
		ts, err := time.Parse(time.RFC3339Nano, p.Timestamp)
		if err != nil {
			return replay.ErrSkip
		}
		if err := orderChangedOnSchema(ctx, mainPool, "shadow_go_port", &p, ts, u.ID, logger); err != nil {
			return fmt.Errorf("shadow_go_port: %w", err)
		}
		if shadowPool != nil {
			if err := orderChangedOnSchema(ctx, shadowPool, "public", &p, ts, u.ID, logger); err != nil {
				return fmt.Errorf("packiot_shadow: %w", err)
			}
		}
		return nil
	}
}

// orderChangedOnSchema applies both the close-old and (optionally)
// create-new steps against a single pool+schema.
func orderChangedOnSchema(ctx context.Context, pool *pgxpool.Pool, schema string, p *OrderChangedPayload, ts time.Time, userLogID int64, logger *slog.Logger) error {
	// Step 1: close old PO
	status := 3 // finish
	if p.StopType == "pause" {
		status = 4
	}
	closeSQL := fmt.Sprintf(`UPDATE %s.production_orders
	   SET status = $1, ts_end = $2, production_final = $3, recalc_needed = true, last_update = now()
	 WHERE id_production_order = $4`, schema)
	_, err := pool.Exec(ctx, closeSQL, status, ts, p.OldProductionOrderProdFinal, p.OldIDProductionOrder)
	if err := failOpenIfMissing(err, "production_orders", schema, userLogID, logger); err != nil {
		return fmt.Errorf("close old PO: %w", err)
	}

	// Step 2 (optional): insert new PO
	if !p.ShouldCreatePo || p.IDOrder == 0 {
		return nil
	}
	// production_programmed + production_ordered both NOT NULL on prod.
	insertSQL := fmt.Sprintf(`INSERT INTO %s.production_orders (
		id_enterprise, id_site, id_area, id_equipment, id_order,
		production_programmed, production_ordered, status, ts_start
	) VALUES ($1,$2,$3,$4,$5,$6,$6,2,$7)
	ON CONFLICT DO NOTHING`, schema)
	_, err = pool.Exec(ctx, insertSQL,
		p.IDEnterprise, p.IDSite, p.IDArea, p.IDEquipment, p.IDOrder,
		p.ProductionOrderQuantity, ts,
	)
	return failOpenIfMissing(err, "production_orders", schema, userLogID, logger)
}
