-- Rollback: restore [0,1] on all four factors. Fails if uncapped rows exist — re-cap them first.
ALTER TABLE gold.production_orders_runtime DROP CONSTRAINT production_orders_runtime_oee_bounds, ADD CONSTRAINT production_orders_runtime_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
ALTER TABLE gold.equipment_oee_hourly DROP CONSTRAINT equipment_oee_hourly_oee_bounds, ADD CONSTRAINT equipment_oee_hourly_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
ALTER TABLE gold.equipment_oee_daily DROP CONSTRAINT equipment_oee_daily_oee_bounds, ADD CONSTRAINT equipment_oee_daily_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
ALTER TABLE gold.equipment_oee_monthly DROP CONSTRAINT equipment_oee_monthly_oee_bounds, ADD CONSTRAINT equipment_oee_monthly_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
ALTER TABLE gold.area_oee_daily DROP CONSTRAINT area_oee_daily_oee_bounds, ADD CONSTRAINT area_oee_daily_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
ALTER TABLE gold.area_oee_shift DROP CONSTRAINT area_oee_shift_oee_bounds, ADD CONSTRAINT area_oee_shift_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
ALTER TABLE gold.site_oee_shift DROP CONSTRAINT site_oee_shift_oee_bounds, ADD CONSTRAINT site_oee_shift_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
ALTER TABLE gold.equipment_oee_shift DROP CONSTRAINT equipment_oee_shift_oee_bounds, ADD CONSTRAINT equipment_oee_shift_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
ALTER TABLE gold.equipment_oee_shift_weekly DROP CONSTRAINT equipment_oee_shift_weekly_oee_bounds, ADD CONSTRAINT equipment_oee_shift_weekly_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
ALTER TABLE gold.equipment_oee_shift_monthly DROP CONSTRAINT equipment_oee_shift_monthly_oee_bounds, ADD CONSTRAINT equipment_oee_shift_monthly_oee_bounds CHECK (oee BETWEEN 0 AND 1 AND oee_a BETWEEN 0 AND 1 AND oee_p BETWEEN 0 AND 1 AND oee_q BETWEEN 0 AND 1) NOT VALID;
