#!/bin/bash
# Production Superset host init — installs Docker + nginx + Certbot, clones the
# stack, and brings up ONLY the `superset` compose profile (persistent). Runs once
# on first boot (fetched from S3 by the instance's inline bootstrap). Logs to
# /var/log/packiot-superset-init.log.
#
# Mirrors terraform/production/user_data/app_init.sh conventions (secrets from
# Secrets Manager → .env, PAT-embedded git clone, certbot DNS-01 wildcard cert),
# trimmed to what a single-purpose BI box needs (no service plane, no GH runner,
# no local DB — the metadata DB is the r7g, reached via POSTGRES_HOST_UPSTREAM).
set -euo pipefail
exec > >(tee /var/log/packiot-superset-init.log | logger -t packiot-superset-init) 2>&1

export HOME=/root
export PATH="/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/bin:$$PATH"

echo "=== Packiot Superset init starting $$(date -u) ==="
AWS_REGION="${aws_region}"
PRODUCTION_DOMAIN="${production_domain}"
GITHUB_REPO="${github_repo}"
STATE_BUCKET="${state_bucket}"
SUPERSET_HOST="${superset_subdomain}.${production_domain}"
POSTGRES_HOST_UPSTREAM="${db_private_ip}"

# ── SSM agent (not pre-installed on AL2023 arm64) ────────────────────────────
dnf install -y amazon-ssm-agent
systemctl enable --now amazon-ssm-agent

# ── System packages ──────────────────────────────────────────────────────────
dnf update -y --allowerasing
dnf install -y git curl unzip jq python3-pip nginx --allowerasing

# ── Swap (headroom for the arm64 Superset image build + gunicorn/celery) ─────
if [ ! -f /swapfile ]; then
  fallocate -l 4G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
fi
swapon /swapfile 2>/dev/null || true
grep -q '^/swapfile ' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
echo "Swap: $$(free -h | awk '/Swap:/ {print $$2}') configured"

# ── Docker + Compose v2 ───────────────────────────────────────────────────────
dnf install -y docker
systemctl enable --now docker
DOCKER_COMPOSE_VERSION="2.27.0"
mkdir -p /usr/local/lib/docker/cli-plugins
curl -SL "https://github.com/docker/compose/releases/download/v$${DOCKER_COMPOSE_VERSION}/docker-compose-linux-aarch64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
docker compose version
echo "Docker + Compose installed"

# ── Fetch secrets → .env ──────────────────────────────────────────────────────
get_secret() {
  aws secretsmanager get-secret-value --secret-id "$$1" --region "$$AWS_REGION" \
    --query SecretString --output text
}
DB_SECRET=$$(get_secret "packiot/production/db")
APP_SECRET=$$(get_secret "packiot/production/app")

DB_USER=$$(echo "$$DB_SECRET" | jq -r '.user')
DB_NAME=$$(echo "$$DB_SECRET" | jq -r '.name')
DB_PASS=$$(echo "$$DB_SECRET" | jq -r '.password')

# SUPERSET_* keys — read with `// ""` so a not-yet-populated key does not crash the
# boot (jq -e would). If any required one is empty the compose bring-up below is
# skipped with a clear log (follow-up 2: populate packiot/production/app).
SUPERSET_SECRET_KEY=$$(echo "$$APP_SECRET" | jq -r '.superset_secret_key // ""')
SUPERSET_GUEST_TOKEN_JWT_SECRET=$$(echo "$$APP_SECRET" | jq -r '.superset_guest_token_jwt_secret // ""')
SUPERSET_DB_PASSWORD=$$(echo "$$APP_SECRET" | jq -r '.superset_db_password // ""')
SUPERSET_DB_RO_PASSWORD=$$(echo "$$APP_SECRET" | jq -r '.superset_db_ro_password // ""')
SUPERSET_GUESTTOKEN_ADMIN_USER=$$(echo "$$APP_SECRET" | jq -r '.superset_guesttoken_admin_user // ""')
SUPERSET_GUESTTOKEN_ADMIN_PASSWORD=$$(echo "$$APP_SECRET" | jq -r '.superset_guesttoken_admin_password // ""')
SUPERSET_COGNITO_ISSUER=$$(echo "$$APP_SECRET" | jq -r '.superset_cognito_issuer // ""')
SUPERSET_COGNITO_CLIENT_ID=$$(echo "$$APP_SECRET" | jq -r '.superset_cognito_client_id // ""')
SUPERSET_COGNITO_CLIENT_SECRET=$$(echo "$$APP_SECRET" | jq -r '.superset_cognito_client_secret // ""')
SUPERSET_OEE_DASHBOARD_UUID=$$(echo "$$APP_SECRET" | jq -r '.superset_oee_dashboard_uuid // ""')

# X-Origin-Verify origin-lock secret (bi_edge.tf): CloudFront stamps this header on
# every origin request; nginx below 403s anything lacking it so the box is only
# reachable through CloudFront. Read with `// ""` so a not-yet-created secret does
# NOT lock the box (empty → guard is skipped, bi reachable directly). Dedicated
# secret (not in packiot/production/app) — its own resource in bi_edge.tf.
BI_ORIGIN_VERIFY=$$(get_secret "packiot/production/bi-origin-verify" 2>/dev/null | jq -r '.value // ""' || echo "")

mkdir -p /opt/packiot
if [ -f /opt/packiot/.env ]; then
  echo ".env already exists — skipping generation"
else
  cat > /opt/packiot/.env <<ENV
# Generated by superset_init.sh — do not edit manually.
PRODUCTION_DOMAIN=$$PRODUCTION_DOMAIN

# Metadata DB (r7g upstream-direct — pgbouncer routes only packiot/packiot_shadow)
POSTGRES_HOST_UPSTREAM=$$POSTGRES_HOST_UPSTREAM
POSTGRES_PORT=5432
POSTGRES_USER=$$DB_USER
POSTGRES_DB=$$DB_NAME
POSTGRES_PASSWORD=$$DB_PASS

# Superset (populate the SUPERSET_* keys in packiot/production/app — follow-up 2)
SUPERSET_SECRET_KEY=$$SUPERSET_SECRET_KEY
SUPERSET_GUEST_TOKEN_JWT_SECRET=$$SUPERSET_GUEST_TOKEN_JWT_SECRET
SUPERSET_DB_PASSWORD=$$SUPERSET_DB_PASSWORD
SUPERSET_DB_RO_PASSWORD=$$SUPERSET_DB_RO_PASSWORD
SUPERSET_GUESTTOKEN_ADMIN_USER=$$SUPERSET_GUESTTOKEN_ADMIN_USER
SUPERSET_GUESTTOKEN_ADMIN_PASSWORD=$$SUPERSET_GUESTTOKEN_ADMIN_PASSWORD
SUPERSET_COGNITO_ISSUER=$$SUPERSET_COGNITO_ISSUER
SUPERSET_COGNITO_CLIENT_ID=$$SUPERSET_COGNITO_CLIENT_ID
SUPERSET_COGNITO_CLIENT_SECRET=$$SUPERSET_COGNITO_CLIENT_SECRET
SUPERSET_OEE_DASHBOARD_UUID=$$SUPERSET_OEE_DASHBOARD_UUID
SUPERSET_FRAME_ANCESTOR=https://front.$$PRODUCTION_DOMAIN
ENV
fi

# ── GitHub auth + clone the stack (production branch) ─────────────────────────
GITHUB_PAT=$$(get_secret "packiot/production/github-runner" | jq -r '.pat')
python3 -c "
import re, os, sys
path = '/root/.gitconfig'
if not os.path.exists(path): sys.exit(0)
with open(path) as f: c = f.read()
c = re.sub(r'\[url \"https://x-access-token:[^\"]+@github\.com/packiot/\"\][^\[]*', '', c)
with open(path, 'w') as f: f.write(c)
"
git config --global url."https://x-access-token:$${GITHUB_PAT}@github.com/packiot/".insteadOf "https://github.com/packiot/"

cd /opt/packiot
if [ -d "stack/.git" ]; then
  cd stack && git fetch origin && git checkout production && git pull origin production
  git submodule update --init --force -- edge-api operator || echo "WARNING: submodule update failed — continuing"
  cd /opt/packiot
else
  git clone --branch production "https://x-access-token:$${GITHUB_PAT}@github.com/$${GITHUB_REPO}.git" stack
  cd stack && git submodule update --init -- edge-api operator || true
  cd /opt/packiot
fi
ln -sf /opt/packiot/.env /opt/packiot/stack/.env

# ── nginx + Certbot (DNS-01 wildcard *.prod.packiot.app) ─────────────────────
pip3 install certbot certbot-dns-route53
certbot certonly --dns-route53 \
  --domain "*.$$PRODUCTION_DOMAIN" --domain "$$PRODUCTION_DOMAIN" \
  --email ops@packiot.com --agree-tos --non-interactive \
  --logs-dir /var/log/letsencrypt || echo "WARNING: certbot failed — check /var/log/letsencrypt"

printf 'map $$http_upgrade $$ws_connection {\n    default upgrade;\n    "" close;\n}\n' \
  > /etc/nginx/conf.d/00-websocket.conf

# Origin-lock guard line — only emitted when the X-Origin-Verify secret exists, so
# a missing secret leaves bi reachable (fail-open on config, not a self-lockout).
if [ -n "$$BI_ORIGIN_VERIFY" ]; then
  ORIGIN_LOCK_LINE="    if (\$$http_x_origin_verify != \"$$BI_ORIGIN_VERIFY\") { return 403; }"
  echo "Origin-lock: X-Origin-Verify guard ENABLED on bi nginx"
else
  ORIGIN_LOCK_LINE="    # X-Origin-Verify secret packiot/production/bi-origin-verify empty — origin-lock NOT enforced"
  echo "Origin-lock: secret empty — guard skipped (bi reachable directly)"
fi

cat > /etc/nginx/conf.d/superset.conf <<NGINX
server {
    listen 80;
    server_name $$SUPERSET_HOST;
    return 301 https://\$$host\$$request_uri;
}
server {
    listen 443 ssl;
    server_name $$SUPERSET_HOST;

    ssl_certificate     /etc/letsencrypt/live/$$PRODUCTION_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$$PRODUCTION_DOMAIN/privkey.pem;

    client_max_body_size 32m;

$$ORIGIN_LOCK_LINE

    location / {
        proxy_pass          http://127.0.0.1:8088;
        proxy_set_header    Host \$$host;
        proxy_set_header    X-Real-IP \$$remote_addr;
        proxy_set_header    X-Forwarded-For \$$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto \$$scheme;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade \$$http_upgrade;
        proxy_set_header    Connection \$$ws_connection;
        proxy_read_timeout  120s;
    }
}
NGINX

systemctl enable nginx
if [ -d "/etc/letsencrypt/live/$$PRODUCTION_DOMAIN" ]; then
  nginx -t && systemctl restart nginx && echo "nginx up for $$SUPERSET_HOST"
else
  echo "WARNING: cert missing — nginx not started (fix cert then: nginx -t && systemctl restart nginx)"
fi

# ── CloudWatch agent (disk/memory metrics for the alarm) ──────────────────────
dnf install -y amazon-cloudwatch-agent || true
cat > /opt/aws/amazon-cloudwatch-agent/etc/cwagent-superset.json <<'CWCFG'
{ "metrics": { "namespace": "CWAgent", "metrics_collected": {
  "disk": { "measurement": ["used_percent"], "resources": ["/"] },
  "mem":  { "measurement": ["mem_used_percent"] } } } }
CWCFG
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
  -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/cwagent-superset.json || true

# ── Bring up ONLY the superset profile (persistent) ──────────────────────────
# Gated on: (a) the overlay files present on the production branch (follow-up 3),
# (b) the required SUPERSET_* secrets populated (follow-up 2), and (c) the DB SG
# admitting this box on 5432 (follow-up 1 — superset-db-init connects to the r7g).
cd /opt/packiot/stack
if [ ! -f compose.superset.yml ]; then
  echo "PENDING: compose.superset.yml not on the production branch yet (PR #780). Host is provisioned; run the bring-up once it lands:"
  echo "  cd /opt/packiot/stack && docker compose -f compose.production.yml -f compose.superset.yml up -d --build superset-redis superset-db-init superset-init superset superset-worker"
elif [ -z "$$SUPERSET_SECRET_KEY" ] || [ -z "$$SUPERSET_DB_PASSWORD" ] || [ -z "$$SUPERSET_GUEST_TOKEN_JWT_SECRET" ]; then
  echo "PENDING: required SUPERSET_* secrets not populated in packiot/production/app (follow-up 2). Skipping bring-up."
else
  echo "Bringing up the superset profile..."
  # NAME the superset services explicitly. Without a service list, `up --build`
  # would also build/start every profile-less service in compose.production.yml
  # (the whole base plane), which dies on csadmin's missing Dockerfile.staging.
  # These are exactly the services carrying profiles: ["superset"].
  docker compose -f compose.production.yml -f compose.superset.yml up -d --build \
    superset-redis superset-db-init superset-init superset superset-worker \
    || echo "WARNING: superset bring-up failed — likely the r7g DB SG has not admitted this box yet (follow-up 1). Check: docker logs superset-db-init"
fi

echo "=== Superset init complete $$(date -u) ==="
