-- t278g — fill the remaining self-evident columns in core + customer_reports for 100% column coverage
-- (the per-schema passes documented non-obvious columns; this completes the boilerplate FK/audit/PK
-- columns + the customer_reports business fields, so no column is left undocumented). Idempotent.

COMMENT ON COLUMN core.areas.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN core.areas.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.areas.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.areas.id_site IS 'FK -> core.sites (tenant/hierarchy scope).';
COMMENT ON COLUMN core.areas.updated_at IS 'Row last-update timestamp.';
COMMENT ON COLUMN core.box_production_bridges.id_enterprise IS 'FK -> core.enterprises (tenant scope).';
COMMENT ON COLUMN core.client_descriptors.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN core.client_descriptors.id IS 'Surrogate primary key of client_descriptors.';
COMMENT ON COLUMN core.client_descriptors.updated_at IS 'Row last-update timestamp.';
COMMENT ON COLUMN core.clients.id_client IS 'FK -> core.clients (tenant/hierarchy scope).';
COMMENT ON COLUMN core.clients.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.downtime_reason.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN core.downtime_reason.id IS 'Surrogate primary key of downtime_reason.';
COMMENT ON COLUMN core.downtime_reason.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.downtime_reason.updated_at IS 'Row last-update timestamp.';
COMMENT ON COLUMN core.enterprises.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN core.enterprises.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.enterprises.logo_url IS 'URL of the enterprise logo asset (shown in the UI).';
COMMENT ON COLUMN core.enterprises.updated_at IS 'Row last-update timestamp.';
COMMENT ON COLUMN core.equipment_downtime_reason.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN core.equipment_downtime_reason.id_equipment IS 'FK -> core.equipments (tenant/hierarchy scope).';
COMMENT ON COLUMN core.equipment_downtime_reason.updated_at IS 'Row last-update timestamp.';
COMMENT ON COLUMN core.equipment_scrap_reason.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN core.equipment_scrap_reason.id_equipment IS 'FK -> core.equipments (tenant/hierarchy scope).';
COMMENT ON COLUMN core.equipment_scrap_reason.updated_at IS 'Row last-update timestamp.';
COMMENT ON COLUMN core.equipment_validation_shift.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.equipment_validation_shift.id_equipment IS 'FK -> core.equipments (tenant/hierarchy scope).';
COMMENT ON COLUMN core.equipments.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN core.equipments.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.equipments.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.equipments.id_equipment IS 'FK -> core.equipments (tenant/hierarchy scope).';
COMMENT ON COLUMN core.equipments.id_site IS 'FK -> core.sites (tenant/hierarchy scope).';
COMMENT ON COLUMN core.equipments.updated_at IS 'Row last-update timestamp.';
COMMENT ON COLUMN core.oee_targets.id IS 'Surrogate primary key of oee_targets.';
COMMENT ON COLUMN core.oee_targets.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.oee_targets.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.product_families.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.product_families.id_product_family IS 'Identifier column (id_product_family).';
COMMENT ON COLUMN core.production_orders.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.production_orders.id_client IS 'FK -> core.clients (tenant/hierarchy scope).';
COMMENT ON COLUMN core.production_orders.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.production_orders.id_product IS 'FK -> core.products (tenant/hierarchy scope).';
COMMENT ON COLUMN core.production_orders.id_site IS 'FK -> core.sites (tenant/hierarchy scope).';
COMMENT ON COLUMN core.production_targets.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.production_targets.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.products.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.products.id_product IS 'FK -> core.products (tenant/hierarchy scope).';
COMMENT ON COLUMN core.scrap_reason.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN core.scrap_reason.id IS 'Surrogate primary key of scrap_reason.';
COMMENT ON COLUMN core.scrap_reason.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.scrap_reason.updated_at IS 'Row last-update timestamp.';
COMMENT ON COLUMN core.scrap_targets.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.scrap_targets.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shift_hours.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shift_hours.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shift_hours.id_shift IS 'FK -> core.shifts (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shift_hours.id_shift_hour IS 'Surrogate primary key of shift_hours.';
COMMENT ON COLUMN core.shift_hours.id_site IS 'FK -> core.sites (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shifts_exception_period.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shifts_exception_period.id_equipment IS 'FK -> core.equipments (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shifts.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shifts.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shifts.id_equipment IS 'FK -> core.equipments (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shifts.id_shift IS 'FK -> core.shifts (tenant/hierarchy scope).';
COMMENT ON COLUMN core.shifts.id_site IS 'FK -> core.sites (tenant/hierarchy scope).';
COMMENT ON COLUMN core.sites.created_at IS 'Row creation timestamp.';
COMMENT ON COLUMN core.sites.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.sites.id_site IS 'FK -> core.sites (tenant/hierarchy scope).';
COMMENT ON COLUMN core.sites.updated_at IS 'Row last-update timestamp.';
COMMENT ON COLUMN core.teams.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.teams.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.teams.id_equipment IS 'FK -> core.equipments (tenant/hierarchy scope).';
COMMENT ON COLUMN core.teams.id_site IS 'FK -> core.sites (tenant/hierarchy scope).';
COMMENT ON COLUMN core.teams.id_team IS 'Surrogate primary key of teams.';
COMMENT ON COLUMN core.topic_routing.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN core.topic_routing.id_enterprise IS 'FK -> core.enterprises (tenant/hierarchy scope).';
COMMENT ON COLUMN core.topic_routing.id_equipment IS 'FK -> core.equipments (tenant/hierarchy scope).';
COMMENT ON COLUMN core.topic_routing.id_site IS 'FK -> core.sites (tenant/hierarchy scope).';
COMMENT ON COLUMN customer_reports.boxes.customer_id IS 'Customer discriminator (=6) for the SAP-transform box source.';
COMMENT ON COLUMN customer_reports.boxes.id_area IS 'FK -> core.areas (tenant/hierarchy scope).';
COMMENT ON COLUMN customer_reports.boxes.id_equipment IS 'FK -> core.equipments (tenant/hierarchy scope).';
COMMENT ON COLUMN customer_reports.boxes.id_order IS 'Production order id (text).';
COMMENT ON COLUMN customer_reports.boxes.id_site IS 'FK -> core.sites (tenant/hierarchy scope).';
COMMENT ON COLUMN customer_reports.boxes.label_key IS 'Barcode label key for the box.';
COMMENT ON COLUMN customer_reports.boxes.ts_value IS 'Event timestamp for the box row.';
COMMENT ON COLUMN customer_reports.production_data_sync.createddate IS 'Record creation timestamp (report shape).';
COMMENT ON COLUMN customer_reports.production_data_sync.customer_id IS 'Customer discriminator for the pooled report table (=6 Montebello/Incoplast).';
COMMENT ON COLUMN customer_reports.production_data_sync.final_trans_status IS 'Terminal transfer status of the row to the external system.';
COMMENT ON COLUMN customer_reports.production_data_sync.id_validation IS 'FK to the validation record (identity of the validating action).';
COMMENT ON COLUMN customer_reports.production_data_sync.item IS 'Product/item code for the produced order.';
COMMENT ON COLUMN customer_reports.production_data_sync.job IS 'Production order / job number.';
COMMENT ON COLUMN customer_reports.production_data_sync.jobcompleteddate IS 'Job completion timestamp.';
COMMENT ON COLUMN customer_reports.production_data_sync.jobstartdate IS 'Job start timestamp.';
COMMENT ON COLUMN customer_reports.production_data_sync.jobstatus IS 'Job lifecycle status.';
COMMENT ON COLUMN customer_reports.production_data_sync.last_update IS 'Last-update timestamp (sync bookkeeping).';
COMMENT ON COLUMN customer_reports.production_data_sync.line IS 'Line label (customer report shape).';
COMMENT ON COLUMN customer_reports.production_data_sync.logics IS 'Internal control/logic-branch code for the sync row (Montebello pipeline).';
COMMENT ON COLUMN customer_reports.production_data_sync.nm_user_validation IS 'Name of the user who validated the shift record.';
COMMENT ON COLUMN customer_reports.production_data_sync.packml_topic IS 'SparkPlug packml topic the row was sourced from.';
COMMENT ON COLUMN customer_reports.production_data_sync.prev_indice_geral IS 'Prior value of indice_geral (rolling general index) for delta/change tracking.';
COMMENT ON COLUMN customer_reports.production_data_sync.real_update IS 'Timestamp of the last real (value-changing) update.';
COMMENT ON COLUMN customer_reports.production_data_sync.shift IS 'Shift label (customer report shape).';
COMMENT ON COLUMN customer_reports.production_data_sync.shiftstartdate IS 'Shift start timestamp.';
COMMENT ON COLUMN customer_reports.production_data_sync.site IS 'Site label (customer report shape).';
COMMENT ON COLUMN customer_reports.production_data_sync.supervisorapproveddate IS 'Timestamp of supervisor approval.';
COMMENT ON COLUMN customer_reports.production_data_sync.supervisornotes IS 'Supervisor free-text notes (jsonb).';
COMMENT ON COLUMN customer_reports.production_data_sync.to_delete IS 'Soft-delete flag for the external sync.';
COMMENT ON COLUMN customer_reports.production_data_sync.ts_creation IS 'Row creation timestamp (Packiot side).';
COMMENT ON COLUMN customer_reports.production_data_sync.updateddate IS 'Record update timestamp (report shape).';
COMMENT ON COLUMN customer_reports.sap_data_sync.auftrag_key IS 'Surrogate key for the order (Auftrag).';
COMMENT ON COLUMN customer_reports.sap_data_sync.customer_id IS 'Customer discriminator for the pooled SAP table (=13 Neopac).';
COMMENT ON COLUMN customer_reports.sap_data_sync.id_order_label IS 'Order-label correlation id.';
COMMENT ON COLUMN customer_reports.sap_data_sync.no_order IS 'Order count / number-of-orders in the slice.';
COMMENT ON COLUMN customer_reports.sap_data_sync.shift_start_time IS 'Shift start timestamp.';
COMMENT ON COLUMN customer_reports.shift.customer_id IS 'Customer discriminator (=6) for the pooled shift report.';
COMMENT ON COLUMN customer_reports.shift.day IS 'Report day (date).';
COMMENT ON COLUMN customer_reports.shift.dt_plan_h IS 'Planned downtime, hours.';
COMMENT ON COLUMN customer_reports.shift.dt_unplan_h IS 'Unplanned downtime, hours.';
COMMENT ON COLUMN customer_reports.shift.id_equipment IS 'FK -> core.equipments.';
COMMENT ON COLUMN customer_reports.shift.job IS 'Production order / job number.';
COMMENT ON COLUMN customer_reports.shift.job_sequence IS 'Job sequence timestamp (ordering within the shift).';
COMMENT ON COLUMN customer_reports.shift.line IS 'Line label.';
COMMENT ON COLUMN customer_reports.shift.running IS 'Running (producing) hours.';
COMMENT ON COLUMN customer_reports.shift.shift IS 'Shift label.';
COMMENT ON COLUMN customer_reports.shift.shift_number IS 'Shift ordinal within the day.';
COMMENT ON COLUMN customer_reports.shift.shift_start_time IS '(shift_start_time).';
