-- 13_p4_rename_runtime_uns_subordinate_objects.sql
-- P4 step 2: rename subordinate objects (constraints/indexes/sequence) on the
-- already-renamed equipment_oee_*/equipment_live_*/area_*/site_* tables so their
-- names follow the meaningful-names cutover (runtime_->oee_, uns_->live_).
-- BEHAVIOR-NEUTRAL: renames are OID-tracked (PKs used via column-inference ON
-- CONFLICT in edge-api; FKs/indexes by OID). Hardproofed: 0 fn bodies reference
-- any of these names (0 ON CONSTRAINT refs; 0 name-string refs). production_orders_runtime
-- is NOT renamed (correctly named) so its subordinate objects are left untouched.
-- Reverse: swap old<->new in each statement.
-- (replay-safe 2026-10-08: each rename is guarded — some constraints were staging-only and absent on prod.)
BEGIN;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.area_live_day') AND conname = 'uns_area_current_day_pkey') THEN ALTER TABLE public.area_live_day RENAME CONSTRAINT uns_area_current_day_pkey TO area_live_day_pkey; ELSE RAISE NOTICE 'skip (absent): public.area_live_day.uns_area_current_day_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.area_live_shift') AND conname = 'uns_area_current_shift_pkey') THEN ALTER TABLE public.area_live_shift RENAME CONSTRAINT uns_area_current_shift_pkey TO area_live_shift_pkey; ELSE RAISE NOTICE 'skip (absent): public.area_live_shift.uns_area_current_shift_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.area_oee_daily') AND conname = 'area_runtime_1day_pk') THEN ALTER TABLE public.area_oee_daily RENAME CONSTRAINT area_runtime_1day_pk TO area_oee_daily_pk; ELSE RAISE NOTICE 'skip (absent): public.area_oee_daily.area_runtime_1day_pk'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.area_oee_shift') AND conname = 'area_runtime_shift_oee_bounds') THEN ALTER TABLE public.area_oee_shift RENAME CONSTRAINT area_runtime_shift_oee_bounds TO area_oee_shift_oee_bounds; ELSE RAISE NOTICE 'skip (absent): public.area_oee_shift.area_runtime_shift_oee_bounds'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.area_oee_shift') AND conname = 'area_runtime_shift_pk') THEN ALTER TABLE public.area_oee_shift RENAME CONSTRAINT area_runtime_shift_pk TO area_oee_shift_pk; ELSE RAISE NOTICE 'skip (absent): public.area_oee_shift.area_runtime_shift_pk'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.area_oee_shift') AND conname = 'chk_area_runtime_shift_ts_order') THEN ALTER TABLE public.area_oee_shift RENAME CONSTRAINT chk_area_runtime_shift_ts_order TO chk_area_oee_shift_ts_order; ELSE RAISE NOTICE 'skip (absent): public.area_oee_shift.chk_area_runtime_shift_ts_order'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_live_day') AND conname = 'uns_equipment_current_day_pkey') THEN ALTER TABLE public.equipment_live_day RENAME CONSTRAINT uns_equipment_current_day_pkey TO equipment_live_day_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_live_day.uns_equipment_current_day_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_live_hour') AND conname = 'uns_equipment_current_hour_pkey') THEN ALTER TABLE public.equipment_live_hour RENAME CONSTRAINT uns_equipment_current_hour_pkey TO equipment_live_hour_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_live_hour.uns_equipment_current_hour_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_live_job') AND conname = 'uns_equipment_current_job_id_equipment_fkey') THEN ALTER TABLE public.equipment_live_job RENAME CONSTRAINT uns_equipment_current_job_id_equipment_fkey TO equipment_live_job_id_equipment_fkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_live_job.uns_equipment_current_job_id_equipment_fkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_live_job') AND conname = 'uns_equipment_current_job_pkey') THEN ALTER TABLE public.equipment_live_job RENAME CONSTRAINT uns_equipment_current_job_pkey TO equipment_live_job_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_live_job.uns_equipment_current_job_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_live_metrics') AND conname = 'uns_equipment_current_metrics_id_equipment_key') THEN ALTER TABLE public.equipment_live_metrics RENAME CONSTRAINT uns_equipment_current_metrics_id_equipment_key TO equipment_live_metrics_id_equipment_key; ELSE RAISE NOTICE 'skip (absent): public.equipment_live_metrics.uns_equipment_current_metrics_id_equipment_key'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_live_metrics') AND conname = 'uns_equipment_current_metrics_pk') THEN ALTER TABLE public.equipment_live_metrics RENAME CONSTRAINT uns_equipment_current_metrics_pk TO equipment_live_metrics_pk; ELSE RAISE NOTICE 'skip (absent): public.equipment_live_metrics.uns_equipment_current_metrics_pk'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_live_month') AND conname = 'uns_equipment_current_month_pkey') THEN ALTER TABLE public.equipment_live_month RENAME CONSTRAINT uns_equipment_current_month_pkey TO equipment_live_month_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_live_month.uns_equipment_current_month_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_live_shift') AND conname = 'uns_equipment_current_shift_pkey') THEN ALTER TABLE public.equipment_live_shift RENAME CONSTRAINT uns_equipment_current_shift_pkey TO equipment_live_shift_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_live_shift.uns_equipment_current_shift_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_live_week') AND conname = 'uns_equipment_current_week_pkey') THEN ALTER TABLE public.equipment_live_week RENAME CONSTRAINT uns_equipment_current_week_pkey TO equipment_live_week_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_live_week.uns_equipment_current_week_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_oee_daily') AND conname = 'equipment_runtime_1day_oee_bounds') THEN ALTER TABLE public.equipment_oee_daily RENAME CONSTRAINT equipment_runtime_1day_oee_bounds TO equipment_oee_daily_oee_bounds; ELSE RAISE NOTICE 'skip (absent): public.equipment_oee_daily.equipment_runtime_1day_oee_bounds'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_oee_daily') AND conname = 'equipment_runtime_1day_pkey') THEN ALTER TABLE public.equipment_oee_daily RENAME CONSTRAINT equipment_runtime_1day_pkey TO equipment_oee_daily_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_oee_daily.equipment_runtime_1day_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_oee_hourly') AND conname = 'equipment_runtime_1hour_oee_bounds') THEN ALTER TABLE public.equipment_oee_hourly RENAME CONSTRAINT equipment_runtime_1hour_oee_bounds TO equipment_oee_hourly_oee_bounds; ELSE RAISE NOTICE 'skip (absent): public.equipment_oee_hourly.equipment_runtime_1hour_oee_bounds'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_oee_hourly') AND conname = 'equipment_runtime_1hour_pkey') THEN ALTER TABLE public.equipment_oee_hourly RENAME CONSTRAINT equipment_runtime_1hour_pkey TO equipment_oee_hourly_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_oee_hourly.equipment_runtime_1hour_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_oee_monthly') AND conname = 'equipment_runtime_1month_pkey') THEN ALTER TABLE public.equipment_oee_monthly RENAME CONSTRAINT equipment_runtime_1month_pkey TO equipment_oee_monthly_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_oee_monthly.equipment_runtime_1month_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_oee_shift') AND conname = 'chk_equipment_runtime_shift_ts_order') THEN ALTER TABLE public.equipment_oee_shift RENAME CONSTRAINT chk_equipment_runtime_shift_ts_order TO chk_equipment_oee_shift_ts_order; ELSE RAISE NOTICE 'skip (absent): public.equipment_oee_shift.chk_equipment_runtime_shift_ts_order'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_oee_shift') AND conname = 'equipment_runtime_shift_oee_bounds') THEN ALTER TABLE public.equipment_oee_shift RENAME CONSTRAINT equipment_runtime_shift_oee_bounds TO equipment_oee_shift_oee_bounds; ELSE RAISE NOTICE 'skip (absent): public.equipment_oee_shift.equipment_runtime_shift_oee_bounds'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_oee_shift') AND conname = 'equipment_runtime_shift_pk') THEN ALTER TABLE public.equipment_oee_shift RENAME CONSTRAINT equipment_runtime_shift_pk TO equipment_oee_shift_pk; ELSE RAISE NOTICE 'skip (absent): public.equipment_oee_shift.equipment_runtime_shift_pk'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.equipment_oee_weekly') AND conname = 'equipment_runtime_1week_pkey') THEN ALTER TABLE public.equipment_oee_weekly RENAME CONSTRAINT equipment_runtime_1week_pkey TO equipment_oee_weekly_pkey; ELSE RAISE NOTICE 'skip (absent): public.equipment_oee_weekly.equipment_runtime_1week_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.site_live_day') AND conname = 'uns_site_current_day_pkey') THEN ALTER TABLE public.site_live_day RENAME CONSTRAINT uns_site_current_day_pkey TO site_live_day_pkey; ELSE RAISE NOTICE 'skip (absent): public.site_live_day.uns_site_current_day_pkey'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.site_oee_daily') AND conname = 'site_runtime_1day_pk') THEN ALTER TABLE public.site_oee_daily RENAME CONSTRAINT site_runtime_1day_pk TO site_oee_daily_pk; ELSE RAISE NOTICE 'skip (absent): public.site_oee_daily.site_runtime_1day_pk'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.site_oee_shift') AND conname = 'chk_site_runtime_shift_ts_order') THEN ALTER TABLE public.site_oee_shift RENAME CONSTRAINT chk_site_runtime_shift_ts_order TO chk_site_oee_shift_ts_order; ELSE RAISE NOTICE 'skip (absent): public.site_oee_shift.chk_site_runtime_shift_ts_order'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.site_oee_shift') AND conname = 'site_runtime_shift_oee_bounds') THEN ALTER TABLE public.site_oee_shift RENAME CONSTRAINT site_runtime_shift_oee_bounds TO site_oee_shift_oee_bounds; ELSE RAISE NOTICE 'skip (absent): public.site_oee_shift.site_runtime_shift_oee_bounds'; END IF; END $r$;
DO $r$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass('public.site_oee_shift') AND conname = 'site_runtime_shift_pk') THEN ALTER TABLE public.site_oee_shift RENAME CONSTRAINT site_runtime_shift_pk TO site_oee_shift_pk; ELSE RAISE NOTICE 'skip (absent): public.site_oee_shift.site_runtime_shift_pk'; END IF; END $r$;
DO $r$ BEGIN IF to_regclass('public.equipment_runtime_1hour_id_equipment_idx') IS NOT NULL THEN ALTER INDEX public.equipment_runtime_1hour_id_equipment_idx RENAME TO equipment_oee_hourly_id_equipment_idx; ELSE RAISE NOTICE 'skip (absent): public.equipment_runtime_1hour_id_equipment_idx'; END IF; END $r$;
DO $r$ BEGIN IF to_regclass('public.equipment_runtime_1hour_ts_value_idx') IS NOT NULL THEN ALTER INDEX public.equipment_runtime_1hour_ts_value_idx RENAME TO equipment_oee_hourly_ts_value_idx; ELSE RAISE NOTICE 'skip (absent): public.equipment_runtime_1hour_ts_value_idx'; END IF; END $r$;
DO $r$ BEGIN IF to_regclass('public.equipment_runtime_shift_1month_pk') IS NOT NULL THEN ALTER INDEX public.equipment_runtime_shift_1month_pk RENAME TO equipment_oee_shift_monthly_pk; ELSE RAISE NOTICE 'skip (absent): public.equipment_runtime_shift_1month_pk'; END IF; END $r$;
DO $r$ BEGIN IF to_regclass('public.equipment_runtime_shift_1week_pk') IS NOT NULL THEN ALTER INDEX public.equipment_runtime_shift_1week_pk RENAME TO equipment_oee_shift_weekly_pk; ELSE RAISE NOTICE 'skip (absent): public.equipment_runtime_shift_1week_pk'; END IF; END $r$;
DO $r$ BEGIN IF to_regclass('public.equipment_runtime_shift_ts_range_id_equipment_idx') IS NOT NULL THEN ALTER INDEX public.equipment_runtime_shift_ts_range_id_equipment_idx RENAME TO equipment_oee_shift_ts_range_id_equipment_idx; ELSE RAISE NOTICE 'skip (absent): public.equipment_runtime_shift_ts_range_id_equipment_idx'; END IF; END $r$;
DO $r$ BEGIN IF to_regclass('public.equipment_runtime_shift_ts_value_idx') IS NOT NULL THEN ALTER INDEX public.equipment_runtime_shift_ts_value_idx RENAME TO equipment_oee_shift_ts_value_idx; ELSE RAISE NOTICE 'skip (absent): public.equipment_runtime_shift_ts_value_idx'; END IF; END $r$;
DO $r$ BEGIN IF to_regclass('public.equipment_runtime_shift_id_seq') IS NOT NULL THEN ALTER SEQUENCE public.equipment_runtime_shift_id_seq RENAME TO equipment_oee_shift_id_seq; ELSE RAISE NOTICE 'skip (absent): public.equipment_runtime_shift_id_seq'; END IF; END $r$;
COMMIT;
