#!/bin/bash
# App EC2 bootstrap — installs Docker, Nginx, Certbot, GitHub Actions runner.
# Runs once on first boot via EC2 user data. Logs to /var/log/packiot-app-init.log.
set -euo pipefail
exec > >(tee /var/log/packiot-app-init.log | logger -t packiot-app-init) 2>&1

# Cloud-init doesn't set HOME; git and ssh need it.
export HOME=/root
export PATH="/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/bin:$PATH"

echo "=== Packiot App init starting $(date -u) ==="
AWS_REGION="${aws_region}"
STAGING_DOMAIN="${staging_domain}"
GITHUB_REPO="${github_repo}"
STATE_BUCKET="${state_bucket}"

# ── SSM agent — NOT pre-installed on AL2023 arm64; install it first ──────────
dnf install -y amazon-ssm-agent
systemctl enable amazon-ssm-agent
systemctl start  amazon-ssm-agent

# ── System ────────────────────────────────────────────────────────────────────
# AL2023 ships with curl-minimal which conflicts with curl; --allowerasing lets dnf replace it.
dnf update -y --allowerasing
dnf install -y git curl unzip jq python3-pip --allowerasing

# ── Docker + Docker Compose ───────────────────────────────────────────────────
dnf install -y docker
systemctl enable docker
systemctl start docker

# Docker Compose v2 (plugin, not standalone binary)
DOCKER_COMPOSE_VERSION="2.27.0"
mkdir -p /usr/local/lib/docker/cli-plugins
curl -SL "https://github.com/docker/compose/releases/download/v$${DOCKER_COMPOSE_VERSION}/docker-compose-linux-aarch64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
docker compose version
echo "Docker + Compose installed"

# ── Fetch all staging secrets ─────────────────────────────────────────────────
get_secret() {
  aws secretsmanager get-secret-value \
    --secret-id "$1" \
    --region "$AWS_REGION" \
    --query SecretString \
    --output text
}

DB_SECRET=$(get_secret "packiot/staging/db")
APP_SECRET=$(get_secret "packiot/staging/app")
HASURA_SECRET=$(get_secret "packiot/staging/hasura")
NR_AUTH=$(get_secret "packiot/staging/nodered-auth")

DB_URL=$(echo "$DB_SECRET"     | jq -r '.url')
DB_PASS=$(echo "$DB_SECRET"    | jq -r '.password')
HASURA_ADMIN=$(echo "$HASURA_SECRET" | jq -r '.admin_secret')
# Hasura expects JWT secret as JSON: {"type":"HS256","key":"<secret>"}
HASURA_JWT_KEY=$(echo "$HASURA_SECRET" | jq -r '.jwt_secret')
HASURA_JWT_JSON="{\"type\":\"HS256\",\"key\":\"$HASURA_JWT_KEY\"}"
API_KEY=$(echo "$APP_SECRET"   | jq -r '.edge_api_key')
MQ_USER=$(echo "$APP_SECRET"   | jq -r '.rabbitmq_user')
MQ_PASS=$(echo "$APP_SECRET"   | jq -r '.rabbitmq_password')
GRAFANA_PASS=$(echo "$APP_SECRET" | jq -r '.grafana_admin_pass')
NR_USER=$(echo "$NR_AUTH" | jq -r '.username')
NR_PASS=$(echo "$NR_AUTH" | jq -r '.password')

# Bcrypt hash for Node-RED adminAuth — settings.js expects $2b$ format (rounds=8).
pip3 install bcrypt --quiet
NR_HASH=$(python3 -c "import bcrypt; print(bcrypt.hashpw(b'$NR_PASS', bcrypt.gensalt(rounds=8)).decode())")

# ── Write .env for Docker Compose ─────────────────────────────────────────────
mkdir -p /opt/packiot
# Guard: skip .env regeneration if it already exists.
# NODE_RED_CREDENTIAL_SECRET must stay stable — Node-RED uses it to decrypt
# flows_cred.json; regenerating it on a re-run makes credentials unreadable.
if [ -f /opt/packiot/.env ]; then
  echo ".env already exists — skipping generation to preserve NODE_RED_CREDENTIAL_SECRET"
else
  NR_SECRET=$(openssl rand -hex 32)

  cat > /opt/packiot/.env <<ENV
# Generated by app_init.sh — do not edit manually.
# Shared by all Docker Compose services via env_file + variable substitution.

# Postgres (DB EC2, private subnet)
POSTGRES_URL=$DB_URL
POSTGRES_HOST=${db_private_ip}
POSTGRES_PORT=5432
POSTGRES_USER=${db_user}
POSTGRES_DB=${db_name}
POSTGRES_PASSWORD=$DB_PASS

# Hasura
HASURA_GRAPHQL_DATABASE_URL=$DB_URL
HASURA_GRAPHQL_ADMIN_SECRET=$HASURA_ADMIN
HASURA_GRAPHQL_JWT_SECRET=$HASURA_JWT_JSON
HASURA_GRAPHQL_ENABLE_CONSOLE=true
HASURA_GRAPHQL_DEV_MODE=false

# Edge API / Node-RED
EDGE_API_KEY=$API_KEY
EDGE_API_URL=https://api.$STAGING_DOMAIN
NODE_RED_CREDENTIAL_SECRET=$NR_SECRET
NODE_RED_ADMIN_USERNAME=$NR_USER
NODE_RED_ADMIN_PASSWORD_HASH=$NR_HASH
# Set after enterprise onboarding via edge-api:
#   ID_ENTERPRISE=<id>
ID_ENTERPRISE=

# RabbitMQ
RABBITMQ_USER=$MQ_USER
RABBITMQ_PASSWORD=$MQ_PASS
RABBITMQ_URL=amqp://$MQ_USER:$MQ_PASS@rabbitmq:5672

# Grafana
GRAFANA_ADMIN_PASSWORD=$GRAFANA_PASS
GF_SERVER_ROOT_URL=https://grafana.$STAGING_DOMAIN

# Compose substitution helpers
STAGING_DOMAIN=$STAGING_DOMAIN
ENV
fi

# ── GitHub auth ───────────────────────────────────────────────────────────────
# Deploy key: SSH auth for the main packiot-stack-alpha repo (git@ URL).
# PAT: HTTPS auth for submodules (edge-api, edge-node-red, oeecloud-node-red).
# GitHub deploy keys are per-repo and can't be shared, so submodules use a PAT.
DEPLOY_KEY_SECRET=$(get_secret "packiot/staging/github-deploy-key")
DEPLOY_KEY=$(echo "$DEPLOY_KEY_SECRET" | jq -r '.private_key')
GITHUB_PAT=$(get_secret "packiot/staging/github-pat" | jq -r '.token')

mkdir -p /root/.ssh
chmod 700 /root/.ssh
printf '%s\n' "$DEPLOY_KEY" > /root/.ssh/github_deploy_key
chmod 600 /root/.ssh/github_deploy_key

cat >> /root/.ssh/config <<SSH_CFG
Host github.com
    HostName github.com
    User git
    IdentityFile /root/.ssh/github_deploy_key
    StrictHostKeyChecking accept-new
SSH_CFG
chmod 600 /root/.ssh/config

echo "GitHub auth configured"

# ── Clone / update repo ───────────────────────────────────────────────────────
export GIT_SSH_COMMAND="ssh -i /root/.ssh/github_deploy_key -o StrictHostKeyChecking=accept-new"
# Rewrite HTTPS submodule URLs to authenticated HTTPS using the PAT.
git config --global url."https://x-access-token:$GITHUB_PAT@github.com/".insteadOf "https://github.com/"

cd /opt/packiot
if [ -d "stack/.git" ]; then
  cd stack
  git pull
  # Non-fatal: if the submodule pointer references a not-yet-pushed commit,
  # warn and continue with the already-checked-out state rather than aborting.
  git submodule update --init -- edge-api edge-node-red oeecloud-node-red \
    || echo "WARNING: submodule update failed — continuing with existing state"
  cd /opt/packiot
else
  git clone git@github.com:$GITHUB_REPO.git stack
  cd stack
  git submodule update --init -- edge-api edge-node-red oeecloud-node-red
  cd /opt/packiot
fi

# Symlink .env into the repo so Docker Compose auto-loads it for variable substitution.
ln -sf /opt/packiot/.env /opt/packiot/stack/.env

# ── Nginx + Certbot ───────────────────────────────────────────────────────────
# nginx_setup.sh is the canonical script — also safe to run standalone for repairs.
aws s3 cp "s3://$STATE_BUCKET/scripts/nginx_setup.sh" /tmp/nginx_setup.sh \
  --region "$AWS_REGION"
bash /tmp/nginx_setup.sh

# ── GitHub Actions self-hosted runner ─────────────────────────────────────────
# The runner registers against the repo and listens for workflow jobs tagged
# with runs-on: [self-hosted, staging].
# Registration token is short-lived; it's fetched from Secrets Manager and
# used once. Subsequent runner auth uses ~/.config/actions-runner/.credentials.

RUNNER_VERSION="2.316.1"
RUNNER_ARCH="arm64"
mkdir -p /opt/actions-runner
cd /opt/actions-runner

curl -sLO "https://github.com/actions/runner/releases/download/v$${RUNNER_VERSION}/actions-runner-linux-$${RUNNER_ARCH}-$${RUNNER_VERSION}.tar.gz"
tar xzf "actions-runner-linux-$${RUNNER_ARCH}-$${RUNNER_VERSION}.tar.gz"
rm "actions-runner-linux-$${RUNNER_ARCH}-$${RUNNER_VERSION}.tar.gz"

# Create a helper script for (re-)registering the runner.
# Run this manually after populating the github-runner secret in Secrets Manager.
cat > /opt/packiot/register-runner.sh <<'SCRIPT'
#!/bin/bash
set -euo pipefail
SECRET=$(aws secretsmanager get-secret-value \
  --secret-id packiot/staging/github-runner \
  --region "${aws_region}" \
  --query SecretString \
  --output text)
PAT=$(echo  "$SECRET" | jq -r '.pat')
REPO=$(echo "$SECRET" | jq -r '.repo')

# Exchange long-lived PAT for a short-lived (1h) registration token via GitHub API
REG_TOKEN=$(curl -sf -X POST \
  -H "Authorization: token $PAT" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$REPO/actions/runners/registration-token" \
  | jq -r '.token')

cd /opt/actions-runner

# Idempotent: stop and uninstall existing service before re-registering
if [ -f /opt/actions-runner/.service ]; then
  ./svc.sh stop    || true
  ./svc.sh uninstall || true
fi

./config.sh \
  --url "https://github.com/$REPO" \
  --token "$REG_TOKEN" \
  --name "staging-$(hostname)" \
  --labels "self-hosted,staging,linux,arm64" \
  --unattended \
  --replace

./svc.sh install root
./svc.sh start
echo "Runner registered and running"
SCRIPT
chmod +x /opt/packiot/register-runner.sh

echo "Runner binaries ready. Run: sudo /opt/packiot/register-runner.sh"
echo "  (after populating packiot/staging/github-runner in Secrets Manager)"

# ── SSM Agent ─────────────────────────────────────────────────────────────────
systemctl enable amazon-ssm-agent
systemctl start amazon-ssm-agent

# ── Start Docker Compose stack ────────────────────────────────────────────────
cd /opt/packiot/stack
docker compose -f compose.staging.yml up -d --build
echo "Docker Compose stack started"
echo "NOTE: set ID_ENTERPRISE in /opt/packiot/.env after enterprise onboarding, then:"
echo "      docker compose -f compose.staging.yml restart edge-nodered oeecloud"

echo "=== App init complete $(date -u) ==="
