#!/bin/bash
# App EC2 bootstrap — installs Docker, Nginx, Certbot, GitHub Actions runner.
# Runs once on first boot via EC2 user data. Logs to /var/log/packiot-app-init.log.
set -euo pipefail
exec > >(tee /var/log/packiot-app-init.log | logger -t packiot-app-init) 2>&1

echo "=== Packiot App init starting $(date -u) ==="
AWS_REGION="${aws_region}"
STAGING_DOMAIN="${staging_domain}"
GITHUB_REPO="${github_repo}"

# ── System ────────────────────────────────────────────────────────────────────
dnf update -y
dnf install -y git curl unzip jq python3-pip

# ── Docker + Docker Compose ───────────────────────────────────────────────────
dnf install -y docker
systemctl enable docker
systemctl start docker

# Docker Compose v2 (plugin, not standalone binary)
DOCKER_COMPOSE_VERSION="2.27.0"
mkdir -p /usr/local/lib/docker/cli-plugins
curl -SL "https://github.com/docker/compose/releases/download/v$${DOCKER_COMPOSE_VERSION}/docker-compose-linux-aarch64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
docker compose version
echo "Docker + Compose installed"

# ── Fetch all staging secrets ─────────────────────────────────────────────────
get_secret() {
  aws secretsmanager get-secret-value \
    --secret-id "$1" \
    --region "$AWS_REGION" \
    --query SecretString \
    --output text
}

DB_SECRET=$(get_secret "packiot/staging/db")
APP_SECRET=$(get_secret "packiot/staging/app")
HASURA_SECRET=$(get_secret "packiot/staging/hasura")

DB_URL=$(echo "$DB_SECRET"     | jq -r '.url')
DB_PASS=$(echo "$DB_SECRET"    | jq -r '.password')
HASURA_ADMIN=$(echo "$HASURA_SECRET" | jq -r '.admin_secret')
# Hasura expects JWT secret as JSON: {"type":"HS256","key":"<secret>"}
HASURA_JWT_KEY=$(echo "$HASURA_SECRET" | jq -r '.jwt_secret')
HASURA_JWT_JSON="{\"type\":\"HS256\",\"key\":\"$HASURA_JWT_KEY\"}"
API_KEY=$(echo "$APP_SECRET"   | jq -r '.edge_api_key')
MQ_USER=$(echo "$APP_SECRET"   | jq -r '.rabbitmq_user')
MQ_PASS=$(echo "$APP_SECRET"   | jq -r '.rabbitmq_password')
GRAFANA_PASS=$(echo "$APP_SECRET" | jq -r '.grafana_admin_pass')

# ── Write .env for Docker Compose ─────────────────────────────────────────────
mkdir -p /opt/packiot
# NODE_RED_CREDENTIAL_SECRET: encrypts credentials.json on disk — generate once.
NR_SECRET=$(openssl rand -hex 32)

cat > /opt/packiot/.env <<ENV
# Generated by app_init.sh — do not edit manually.
# Shared by all Docker Compose services via env_file + variable substitution.

# Postgres (DB EC2, private subnet)
POSTGRES_URL=$DB_URL
POSTGRES_HOST=${db_private_ip}
POSTGRES_PORT=5432
POSTGRES_USER=${db_user}
POSTGRES_DB=${db_name}
POSTGRES_PASSWORD=$DB_PASS

# Hasura
HASURA_GRAPHQL_DATABASE_URL=$DB_URL
HASURA_GRAPHQL_ADMIN_SECRET=$HASURA_ADMIN
HASURA_GRAPHQL_JWT_SECRET=$HASURA_JWT_JSON
HASURA_GRAPHQL_ENABLE_CONSOLE=true
HASURA_GRAPHQL_DEV_MODE=false

# Edge API / Node-RED
EDGE_API_KEY=$API_KEY
EDGE_API_URL=https://api.$STAGING_DOMAIN
NODE_RED_CREDENTIAL_SECRET=$NR_SECRET
# Set after enterprise onboarding via edge-api:
#   ID_ENTERPRISE=<id>
ID_ENTERPRISE=

# RabbitMQ
RABBITMQ_USER=$MQ_USER
RABBITMQ_PASSWORD=$MQ_PASS
RABBITMQ_URL=amqp://$MQ_USER:$MQ_PASS@rabbitmq:5672

# Grafana
GRAFANA_ADMIN_PASSWORD=$GRAFANA_PASS
GF_SERVER_ROOT_URL=https://grafana.$STAGING_DOMAIN

# Compose substitution helpers
STAGING_DOMAIN=$STAGING_DOMAIN
ENV

# ── Clone / update repo ───────────────────────────────────────────────────────
cd /opt/packiot
git clone --recurse-submodules https://github.com/$GITHUB_REPO.git stack 2>/dev/null || \
  (cd stack && git pull && git submodule update --init --recursive)

# Symlink .env into the repo so Docker Compose auto-loads it for variable substitution.
ln -sf /opt/packiot/.env /opt/packiot/stack/.env

# ── Nginx ─────────────────────────────────────────────────────────────────────
dnf install -y nginx
systemctl enable nginx

# Write a server block for each service.
# Initially plain HTTP; Certbot will rewrite to HTTPS.
%{ for svc, port in services ~}
cat > /etc/nginx/conf.d/${svc}.conf <<NGINX
server {
    listen 80;
    server_name ${svc}.$STAGING_DOMAIN;

    location / {
        proxy_pass         http://127.0.0.1:${port};
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
    }
}
NGINX
%{ endfor ~}

nginx -t && systemctl start nginx
echo "Nginx configured for: %{ for svc, _ in services }${svc} %{ endfor }"

# ── Certbot + Let's Encrypt (DNS-01 via Route53) ──────────────────────────────
# DNS-01 challenge: Certbot creates a TXT record in Route53, Let's Encrypt
# verifies it, no inbound port 80 challenge needed.
# The App EC2 IAM role has route53:ChangeResourceRecordSets permission.
pip3 install certbot certbot-dns-route53

# Request wildcard cert for *.staging.packiot.com — covers all service subdomains.
certbot certonly \
  --dns-route53 \
  --domain "*.$STAGING_DOMAIN" \
  --domain "$STAGING_DOMAIN" \
  --email ops@packiot.com \
  --agree-tos \
  --non-interactive \
  --logs-dir /var/log/letsencrypt || echo "WARNING: certbot failed — check DNS delegation"

# Rewrite Nginx configs to use HTTPS once the cert exists
if [ -d "/etc/letsencrypt/live/$STAGING_DOMAIN" ]; then
%{ for svc, port in services ~}
  cat > /etc/nginx/conf.d/${svc}.conf <<NGINX
server {
    listen 80;
    server_name ${svc}.$STAGING_DOMAIN;
    return 301 https://\$host\$request_uri;
}
server {
    listen 443 ssl;
    server_name ${svc}.$STAGING_DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$STAGING_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$STAGING_DOMAIN/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_pass         http://127.0.0.1:${port};
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_read_timeout 300s;
    }
}
NGINX
%{ endfor ~}
  nginx -t && nginx -s reload
  echo "HTTPS configured for all services"
fi

# Auto-renew cert (Let's Encrypt certs expire after 90 days).
echo "0 3 * * * root certbot renew --quiet && nginx -s reload" \
  > /etc/cron.d/certbot-renew

# ── GitHub Actions self-hosted runner ─────────────────────────────────────────
# The runner registers against the repo and listens for workflow jobs tagged
# with runs-on: [self-hosted, staging].
# Registration token is short-lived; it's fetched from Secrets Manager and
# used once. Subsequent runner auth uses ~/.config/actions-runner/.credentials.

RUNNER_VERSION="2.316.1"
RUNNER_ARCH="arm64"
mkdir -p /opt/actions-runner
cd /opt/actions-runner

curl -sLO "https://github.com/actions/runner/releases/download/v$${RUNNER_VERSION}/actions-runner-linux-$${RUNNER_ARCH}-$${RUNNER_VERSION}.tar.gz"
tar xzf "actions-runner-linux-$${RUNNER_ARCH}-$${RUNNER_VERSION}.tar.gz"
rm "actions-runner-linux-$${RUNNER_ARCH}-$${RUNNER_VERSION}.tar.gz"

# Create a helper script for (re-)registering the runner.
# Run this manually after populating the github-runner secret in Secrets Manager.
cat > /opt/packiot/register-runner.sh <<'SCRIPT'
#!/bin/bash
set -euo pipefail
SECRET=$(aws secretsmanager get-secret-value \
  --secret-id packiot/staging/github-runner \
  --region "${aws_region}" \
  --query SecretString \
  --output text)
TOKEN=$(echo "$SECRET" | jq -r '.registration_token')
REPO=$(echo  "$SECRET" | jq -r '.repo')

cd /opt/actions-runner
./config.sh \
  --url "https://github.com/$REPO" \
  --token "$TOKEN" \
  --name "staging-$(hostname)" \
  --labels "self-hosted,staging,linux,arm64" \
  --unattended \
  --replace

# Install and start as a systemd service
./svc.sh install root
./svc.sh start
echo "Runner registered and running"
SCRIPT
chmod +x /opt/packiot/register-runner.sh

echo "Runner binaries ready. Run: sudo /opt/packiot/register-runner.sh"
echo "  (after populating packiot/staging/github-runner in Secrets Manager)"

# ── SSM Agent ─────────────────────────────────────────────────────────────────
systemctl enable amazon-ssm-agent
systemctl start amazon-ssm-agent

# ── Start Docker Compose stack ────────────────────────────────────────────────
cd /opt/packiot/stack
docker compose -f compose.staging.yml up -d --build
echo "Docker Compose stack started"
echo "NOTE: set ID_ENTERPRISE in /opt/packiot/.env after enterprise onboarding, then:"
echo "      docker compose -f compose.staging.yml restart edge-nodered oeecloud"

echo "=== App init complete $(date -u) ==="
