-- ADR-0012 Phase 3: writer-target tables for the live-data POC.
--
-- The Hasura metadata-parity stub (17-hasura-metadata-parity.sql) only
-- creates tables Hasura tracks — this excludes the RAW hypertables
-- oeecloud-worker writes to (equipment_values, uns_equipment_current_metrics)
-- because prod Hasura reads from the CAggs on top of these, not the raw
-- hypertables themselves.
--
-- For the live-data POC (source_type="refactored" → packiot_shadow), the
-- worker still needs to INSERT to equipment_values + uns_equipment_current_metrics.
-- This script creates them as REGULAR tables (not hypertables — the
-- sandbox POC doesn't need chunking, just structural parity for the write path).
--
-- Column shapes match prod tsp12 (`packiot40`), captured 2026-07-01
-- via SELECT on information_schema.columns.

CREATE TABLE IF NOT EXISTS public.equipment_values (
    ts_value                       timestamp with time zone NOT NULL,
    id_enterprise                  integer NOT NULL,
    id_site                        integer NOT NULL,
    id_area                        integer NOT NULL,
    id_equipment                   integer NOT NULL,
    net_production_incr            double precision,
    gross_production_incr          double precision,
    scrap_incr                     double precision,
    speed                          real,
    id_order                       character varying,
    conversion_factor              real,
    number_cavities                integer,
    faults                         jsonb,
    analogs                        jsonb,
    signal_quality                 smallint,
    net_production_val             double precision,
    gross_production_val           double precision,
    scrap_val                      double precision,
    id_shift                       integer,
    id_team                        integer,
    id_shift_hour                  integer,
    box_code                       character varying,
    transaction_code               character varying,
    state                          integer,
    mode                           integer,
    id_production_order            bigint,
    ts_value_production            date,
    id_equipment_line_infeed       integer,
    id_equipment_line_outfeed      integer,
    net_production_incr_quality    smallint,
    gross_production_incr_quality  smallint,
    scrap_incr_quality             smallint,
    speed_quality                  smallint,
    id_order_quality               smallint,
    conversion_factor_quality      smallint,
    number_cavities_quality        smallint,
    net_production_val_quality     smallint,
    gross_production_val_quality   smallint,
    scrap_val_quality              smallint,
    id_shift_quality               smallint,
    state_quality                  smallint,
    mode_quality                   smallint,
    id_production_order_quality    smallint,
    ts_value_production_quality    smallint,
    id_equipment_line_connected    integer,
    position_in_equipment_line     smallint,
    is_equipment_line_infeed       smallint,
    is_equipment_line_outfeed      smallint,
    process_scrap_incr             double precision,
    process_scrap_val              double precision,
    process_scrap_incr_quality     smallint,
    process_scrap_val_quality      smallint,
    tp_equipment                   smallint,
    sub_mode                       character varying,
    ideal_production_speed         integer,
    check_number                   bigint,
    PRIMARY KEY (ts_value, id_equipment)
);
CREATE INDEX IF NOT EXISTS equipment_values_id_equipment_ts_idx ON public.equipment_values (id_equipment, ts_value DESC);

CREATE TABLE IF NOT EXISTS public.uns_equipment_current_metrics (
    id_equipment integer PRIMARY KEY,
    ts_value     timestamp with time zone NOT NULL,
    payload      jsonb
);

-- packml_register — the topic→equipment resolver. The worker uses the
-- MAIN pool for resolver lookups (not the shadow pool), so this table
-- exists on `packiot` DB and is NOT needed on `packiot_shadow`. Skipping.

-- ADR-0013 shadow-mirror target tables. Column shape captured from
-- staging packiot 2026-07-02 (matches prod tsp12).

CREATE TABLE IF NOT EXISTS public.equipment_events_man (
    id_equipment           integer,
    ts_event               timestamp with time zone,
    status                 integer,
    id_equipment_event     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txt_downtime_notes     text,
    idle                   character varying,
    idle_processed         boolean,
    forced_creation_system boolean,
    fault                  integer,
    fault_processed        boolean,
    cd_machine             character varying,
    cd_category            character varying,
    cd_subcategory         character varying,
    change_over            boolean,
    planned_downtime       boolean,
    ts_end                 timestamp with time zone,
    duration               integer,
    id_enterprise          integer,
    desc_category          character varying,
    desc_subcategory       character varying,
    cd_category_client     integer,
    cd_subcategory_client  integer,
    last_update            timestamp with time zone DEFAULT now(),
    ignore_cost            boolean
);
CREATE INDEX IF NOT EXISTS eem_id_equipment_ts_idx ON public.equipment_events_man (id_equipment, ts_event DESC);
-- ts_event is equipment_events_man's PRIMARY KEY on packiot.public
-- (prod shape) — globally unique. The shadow copy needs the same rule:
-- shadow-mirror's ON CONFLICT (ts_event) idempotency depends on it, and
-- without it cursor re-replays accumulate duplicate rows (observed:
-- 102 dupes before this landed).
CREATE UNIQUE INDEX IF NOT EXISTS equipment_events_man_ts_event_key
    ON public.equipment_events_man (ts_event);

CREATE TABLE IF NOT EXISTS public.production_orders (
    id_production_order            bigint GENERATED BY DEFAULT AS IDENTITY,
    id_enterprise                  integer NOT NULL,
    id_site                        integer NOT NULL,
    id_area                        integer NOT NULL,
    id_equipment                   integer NOT NULL,
    id_product                     integer,
    id_client                      integer,
    status                         integer DEFAULT 1 NOT NULL,
    production_programmed          bigint,
    production_ordered             bigint,
    id_order                       integer NOT NULL,
    id_user_operator               integer,
    id_equipment_executed          integer,
    production_real                bigint,
    production_final               bigint,
    ts_start                       timestamp with time zone,
    ts_end                         timestamp with time zone,
    equipment_setup                jsonb,
    oee_processed                  boolean DEFAULT false NOT NULL,
    oee                            real,
    stopped_time                   integer,
    planned_downtime               integer,
    qt_stops                       integer,
    erp_processed                  boolean DEFAULT false NOT NULL,
    ts_creation                    timestamp with time zone DEFAULT now() NOT NULL,
    txt_production_order_notes     character varying(255),
    txt_production_order_description character varying(255),
    conversion_factor              real DEFAULT 1,
    net_production                 double precision,
    speed                          real,
    ideal_production_speed         integer,
    id_order_text                  character varying(255),
    recalc_needed                  boolean DEFAULT true NOT NULL,
    last_update                    timestamp with time zone DEFAULT now(),
    nm_production_order            character varying,
    multiplier                     double precision,
    PRIMARY KEY (id_production_order)
);
CREATE INDEX IF NOT EXISTS po_id_equipment_status_idx ON public.production_orders (id_equipment, status);

-- Bugs 247/248 (2026-07-02): shadow-mirror replays lifecycle UPDATEs by
-- the natural key (id_enterprise, id_order) — surrogate ids diverge per
-- flow by construction. Both shadow destinations need the same
-- uniqueness rules as packiot.public so (a) the handlers' qualified
-- ON CONFLICT (id_enterprise, id_order) has an index to match and
-- (b) the one-running-PO-per-equipment invariant can't be violated
-- silently on one flow but enforced on the other.
CREATE UNIQUE INDEX IF NOT EXISTS production_orders_id_enterprise_id_order_key
    ON public.production_orders (id_enterprise, id_order);
CREATE UNIQUE INDEX IF NOT EXISTS production_orders_id_equipment_run_idx
    ON public.production_orders (id_equipment) WHERE (status = 2);

\echo ''
\echo '=== packiot_shadow writer-target tables created ==='
SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename IN ('equipment_values','uns_equipment_current_metrics','equipment_events_man','production_orders') ORDER BY tablename;
