global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    env: staging
    cluster: packiot-staging

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: oeecloud-worker
    static_configs:
      - targets: ['oeecloud-worker:9101']
