#!/usr/bin/env bash
# Emit a templated oeecloud-fanout compose-service fragment + .env line for a
# re-tenant TWIN fan-out (task #22 — the one RabbitMQ-topology gap onboarding
# doesn't already cover).
#
# Context (don't re-litigate this while reading the script):
#   - stream-engine (fka oeecloud-worker) AUTO-DECLARES per-tenant queues
#     (stream-engine-q-<tenant> + retry/failed) from packml_register at boot
#     (Strategy D discovery), and the RabbitMQ perms are wildcard-generic
#     (stream-engine-q.*). So a brand-new REAL client needs ZERO manual RMQ
#     step — this script is NOT for that case.
#   - The ONLY gap is a SANDBOX/TWIN tenant (e.g. SBXCPACK, ent 2000003) that
#     should mirror an existing tenant's live SparkPlug stream under a
#     DIFFERENT tenant key (re-tenant fan-out, services/oeecloud-fanout).
#     That needs its own dedicated consumer instance — one compose service
#     per twin, because each twin is a distinct (source, target) pair with
#     its own queue/IP/health-port.
#   - services/oeecloud-fanout is already fully env-driven per instance
#     (FANOUT_SOURCE_GROUP / FANOUT_TARGET_GROUP / FANOUT_QUEUE / routing
#     keys / FANOUT_ENABLED — see internal/config/config.go and the
#     retenant package's Config doc). Nothing in the Go code is
#     CPACK/SBXCPACK-hardcoded; this script is the missing "emit the
#     per-twin compose wiring" piece, so provisioning a new twin doesn't
#     require hand-editing compose.staging.yml.
#
# Usage:
#   scripts/emit-fanout-config.sh SOURCE_GROUP TARGET_GROUP [HEALTH_PORT] [IP_LAST_OCTET]
#
# SOURCE_GROUP / TARGET_GROUP are SparkPlug GroupIDs (== the tenant's first
# topic segment, == packml_register's tenant string lowercased). HEALTH_PORT
# and IP_LAST_OCTET default to the already-deployed CPACK→SBXCPACK instance's
# values (9102 / 172.18.0.41) for that specific pair; ANY other pair MUST pass
# explicit values that are not already taken by another service in
# compose.staging.yml (this script does not scan the network for collisions —
# check by hand, same as adding any other compose service).
#
# Idempotent: re-running with the same args regenerates a byte-identical file
# (pure template, no state, overwrite-not-append). Templatable: works for any
# (source, target) pair, not just CPACK/SBXCPACK — that pair is only this
# script's DEFAULT-documented example, never a hardcoded branch.
#
# Output: writes a ready-to-splice docker-compose fragment to
#   configs/fanout/<target_group_lower>.yml
# and prints the .env flag to set to enable it (default false — the container
# idles healthy until flipped, same posture as the existing instance).
#
# Example (the CPACK -> SANDBOX-CPACK twin already live in compose.staging.yml):
#   scripts/emit-fanout-config.sh CPACK SBXCPACK
#
# Wiring the emitted file into the stack is still a manual step (docker
# compose has no native "load every file under a directory"):
#   docker compose -f compose.staging.yml -f configs/fanout/sbxcpack.yml \
#     up -d oeecloud-fanout-sbxcpack
# or splice the `services:` block into compose.staging.yml directly.
#
# STAGING ONLY — never wire an emitted fan-out service into
# compose.production.yml (see services/oeecloud-fanout/README.md).
set -euo pipefail

usage() {
  echo "usage: $(basename "$0") SOURCE_GROUP TARGET_GROUP [HEALTH_PORT] [IP_LAST_OCTET]" >&2
  exit 2
}

[ $# -ge 2 ] || usage
SRC="$1"
TGT="$2"
HEALTH_PORT="${3:-9102}"
IP_OCTET="${4:-41}"

SRC_UP=$(printf '%s' "$SRC" | tr '[:lower:]' '[:upper:]')
TGT_UP=$(printf '%s' "$TGT" | tr '[:lower:]' '[:upper:]')
SRC_LOW=$(printf '%s' "$SRC" | tr '[:upper:]' '[:lower:]')
TGT_LOW=$(printf '%s' "$TGT" | tr '[:upper:]' '[:lower:]')

SVC_NAME="oeecloud-fanout-${TGT_LOW}"
ENV_FLAG="FANOUT_${SRC_UP}_TO_${TGT_UP}_ENABLED"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$REPO_ROOT/configs/fanout"
OUT_FILE="$OUT_DIR/${TGT_LOW}.yml"
mkdir -p "$OUT_DIR"

cat > "$OUT_FILE" <<YAML
# GENERATED by scripts/emit-fanout-config.sh ${SRC_UP} ${TGT_UP} ${HEALTH_PORT} ${IP_OCTET}
# Re-run the identical command to regenerate deterministically (idempotent —
# do not hand-edit; change the args and re-run instead).
#
# Re-tenant twin fan-out: ${SRC_UP} -> ${TGT_UP} (task #22). STAGING ONLY —
# do not add this service to compose.production.yml. See
# services/oeecloud-fanout/README.md for the double-count / no-loop argument
# and scripts/provision-sandbox-tenant.sh for the twin's DB-side clone.
#
# Splice the service below into compose.staging.yml under services:, OR load
# it as an extra compose file:
#   docker compose -f compose.staging.yml -f configs/fanout/${TGT_LOW}.yml \\
#     up -d ${SVC_NAME}
#
# Before first use: confirm 172.18.0.${IP_OCTET} and health port ${HEALTH_PORT}
# are not already claimed by another service/twin in compose.staging.yml
# (bump HEALTH_PORT/IP_LAST_OCTET and re-run this script if they collide).
# If a service for THIS EXACT ${SRC_UP}->${TGT_UP} pair is already hand-wired
# in compose.staging.yml, do NOT ALSO splice this file in — one source of
# truth per pair (two consumers on the same queue name is harmless but
# wasteful, never do it deliberately).
# Then set ${ENV_FLAG}=true in staging .env and restart ${SVC_NAME}
# to turn the fan-out on (default false — idles healthy, binds no queue).
services:
  ${SVC_NAME}:
    build: ./services/oeecloud-fanout
    container_name: ${SVC_NAME}
    restart: unless-stopped
    env_file: [.env]
    environment:
      LOG_LEVEL: info
      # Master gate for THIS twin only — set ${ENV_FLAG}=true in .env to enable.
      FANOUT_ENABLED: "\${${ENV_FLAG}:-false}"
      AWS_REGION: us-east-1
      # Reuses stream-engine's least-privilege AMQP user (declare own
      # topology, consume own queue, publish to \`oee\`) — no new broker
      # principal needed, same pattern as the existing CPACK->SBXCPACK instance.
      RABBITMQ_SECRET_ID: packiot/staging/rabbitmq-stream-engine-creds
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      SOURCE_EXCHANGE: oee
      FANOUT_QUEUE: oeecloud-fanout-${SRC_LOW}-to-${TGT_LOW}
      FANOUT_SOURCE_GROUP: ${SRC_UP}
      FANOUT_TARGET_GROUP: ${TGT_UP}
      # 2-segment key is the live one (tenant rides inside the envelope); the
      # 3-segment key is bound too so this keeps working if per-tenant
      # routing is ever enabled. See internal/config/config.go.
      FANOUT_SOURCE_ROUTING_KEYS: "sparkplug.data,sparkplug.data.${SRC_LOW}"
      FANOUT_TARGET_ROUTING_KEY: "sparkplug.data.${TGT_LOW}"
      PREFETCH: "50"
      PUBLISH_CONFIRM_TIMEOUT_MS: "5000"
      HEALTH_PORT: "${HEALTH_PORT}"
    networks:
      packiot-net:
        ipv4_address: 172.18.0.${IP_OCTET}
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/local/bin/oeecloud-fanout", "--healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    mem_limit: 128m
    cpus: 0.25
    logging:
      driver: json-file
      options: {max-size: "10m", max-file: "3"}
YAML

echo "wrote $OUT_FILE"
echo
echo "Splice its services: block into compose.staging.yml (or load it as an"
echo "extra -f compose file), then enable in staging .env:"
echo "  ${ENV_FLAG}=true"
echo "and restart: docker compose up -d --build ${SVC_NAME}"
