-- analytics-rename DOWN — restore original runtime_* names
BEGIN;
DROP VIEW public.site_runtime_1month;
ALTER TABLE public.site_oee_monthly RENAME TO site_runtime_1month;
DROP VIEW public.site_runtime_1week;
ALTER TABLE public.site_oee_weekly RENAME TO site_runtime_1week;
DROP VIEW public.site_runtime_1day;
ALTER TABLE public.site_oee_daily RENAME TO site_runtime_1day;
DROP VIEW public.site_runtime_1hour;
ALTER TABLE public.site_oee_hourly RENAME TO site_runtime_1hour;
DROP VIEW public.site_runtime_shift;
ALTER TABLE public.site_oee_shift RENAME TO site_runtime_shift;
DROP VIEW public.area_runtime_1month;
ALTER TABLE public.area_oee_monthly RENAME TO area_runtime_1month;
DROP VIEW public.area_runtime_1week;
ALTER TABLE public.area_oee_weekly RENAME TO area_runtime_1week;
DROP VIEW public.area_runtime_1day;
ALTER TABLE public.area_oee_daily RENAME TO area_runtime_1day;
DROP VIEW public.area_runtime_1hour;
ALTER TABLE public.area_oee_hourly RENAME TO area_runtime_1hour;
DROP VIEW public.area_runtime_shift;
ALTER TABLE public.area_oee_shift RENAME TO area_runtime_shift;
DROP VIEW public.equipment_runtime_shift_1month;
ALTER TABLE public.equipment_oee_shift_monthly RENAME TO equipment_runtime_shift_1month;
DROP VIEW public.equipment_runtime_shift_1week;
ALTER TABLE public.equipment_oee_shift_weekly RENAME TO equipment_runtime_shift_1week;
DROP VIEW public.equipment_runtime_1month;
ALTER TABLE public.equipment_oee_monthly RENAME TO equipment_runtime_1month;
DROP VIEW public.equipment_runtime_1week;
ALTER TABLE public.equipment_oee_weekly RENAME TO equipment_runtime_1week;
DROP VIEW public.equipment_runtime_1day;
ALTER TABLE public.equipment_oee_daily RENAME TO equipment_runtime_1day;
DROP VIEW public.equipment_runtime_1hour;
ALTER TABLE public.equipment_oee_hourly RENAME TO equipment_runtime_1hour;
DROP VIEW public.equipment_runtime_shift;
ALTER TABLE public.equipment_oee_shift RENAME TO equipment_runtime_shift;
COMMIT;
