SET lock_timeout='6s';
BEGIN;
DROP VIEW public.uns_site_current_month;
ALTER TABLE public.site_live_month RENAME TO uns_site_current_month;
DROP VIEW public.uns_site_current_week;
ALTER TABLE public.site_live_week RENAME TO uns_site_current_week;
DROP VIEW public.uns_site_current_day;
ALTER TABLE public.site_live_day RENAME TO uns_site_current_day;
DROP VIEW public.uns_site_current_hour;
ALTER TABLE public.site_live_hour RENAME TO uns_site_current_hour;
DROP VIEW public.uns_area_current_month;
ALTER TABLE public.area_live_month RENAME TO uns_area_current_month;
DROP VIEW public.uns_area_current_week;
ALTER TABLE public.area_live_week RENAME TO uns_area_current_week;
DROP VIEW public.uns_area_current_day;
ALTER TABLE public.area_live_day RENAME TO uns_area_current_day;
DROP VIEW public.uns_area_current_shift;
ALTER TABLE public.area_live_shift RENAME TO uns_area_current_shift;
DROP VIEW public.uns_area_current_hour;
ALTER TABLE public.area_live_hour RENAME TO uns_area_current_hour;
DROP VIEW public.uns_equipment_current_job;
ALTER TABLE public.equipment_live_job RENAME TO uns_equipment_current_job;
DROP VIEW public.uns_equipment_current_month;
ALTER TABLE public.equipment_live_month RENAME TO uns_equipment_current_month;
DROP VIEW public.uns_equipment_current_week;
ALTER TABLE public.equipment_live_week RENAME TO uns_equipment_current_week;
DROP VIEW public.uns_equipment_current_day;
ALTER TABLE public.equipment_live_day RENAME TO uns_equipment_current_day;
DROP VIEW public.uns_equipment_current_shift;
ALTER TABLE public.equipment_live_shift RENAME TO uns_equipment_current_shift;
DROP VIEW public.uns_equipment_current_hour;
ALTER TABLE public.equipment_live_hour RENAME TO uns_equipment_current_hour;
DROP VIEW public.uns_equipment_current_metrics;
ALTER TABLE public.equipment_live_metrics RENAME TO uns_equipment_current_metrics;
COMMIT;
