-- analytics-rename UP #2 — uns_* current-state snapshots -> *_live_* (drop UNS jargon)
-- Same expand/contract mechanism; no RLS on these; unique index per inference col;
-- code ON CONFLICT (col)/bare writers traverse the security_invoker shim (proven).
SET lock_timeout='6s';
BEGIN;
ALTER TABLE public.uns_equipment_current_metrics RENAME TO equipment_live_metrics;
CREATE VIEW public.uns_equipment_current_metrics WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_metrics;
COMMENT ON VIEW public.uns_equipment_current_metrics IS 'compat shim — renamed to equipment_live_metrics 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_equipment_current_hour RENAME TO equipment_live_hour;
CREATE VIEW public.uns_equipment_current_hour WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_hour;
COMMENT ON VIEW public.uns_equipment_current_hour IS 'compat shim — renamed to equipment_live_hour 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_equipment_current_shift RENAME TO equipment_live_shift;
CREATE VIEW public.uns_equipment_current_shift WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_shift;
COMMENT ON VIEW public.uns_equipment_current_shift IS 'compat shim — renamed to equipment_live_shift 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_equipment_current_day RENAME TO equipment_live_day;
CREATE VIEW public.uns_equipment_current_day WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_day;
COMMENT ON VIEW public.uns_equipment_current_day IS 'compat shim — renamed to equipment_live_day 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_equipment_current_week RENAME TO equipment_live_week;
CREATE VIEW public.uns_equipment_current_week WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_week;
COMMENT ON VIEW public.uns_equipment_current_week IS 'compat shim — renamed to equipment_live_week 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_equipment_current_month RENAME TO equipment_live_month;
CREATE VIEW public.uns_equipment_current_month WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_month;
COMMENT ON VIEW public.uns_equipment_current_month IS 'compat shim — renamed to equipment_live_month 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_equipment_current_job RENAME TO equipment_live_job;
CREATE VIEW public.uns_equipment_current_job WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_job;
COMMENT ON VIEW public.uns_equipment_current_job IS 'compat shim — renamed to equipment_live_job 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_area_current_hour RENAME TO area_live_hour;
CREATE VIEW public.uns_area_current_hour WITH (security_invoker=true) AS SELECT * FROM public.area_live_hour;
COMMENT ON VIEW public.uns_area_current_hour IS 'compat shim — renamed to area_live_hour 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_area_current_shift RENAME TO area_live_shift;
CREATE VIEW public.uns_area_current_shift WITH (security_invoker=true) AS SELECT * FROM public.area_live_shift;
COMMENT ON VIEW public.uns_area_current_shift IS 'compat shim — renamed to area_live_shift 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_area_current_day RENAME TO area_live_day;
CREATE VIEW public.uns_area_current_day WITH (security_invoker=true) AS SELECT * FROM public.area_live_day;
COMMENT ON VIEW public.uns_area_current_day IS 'compat shim — renamed to area_live_day 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_area_current_week RENAME TO area_live_week;
CREATE VIEW public.uns_area_current_week WITH (security_invoker=true) AS SELECT * FROM public.area_live_week;
COMMENT ON VIEW public.uns_area_current_week IS 'compat shim — renamed to area_live_week 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_area_current_month RENAME TO area_live_month;
CREATE VIEW public.uns_area_current_month WITH (security_invoker=true) AS SELECT * FROM public.area_live_month;
COMMENT ON VIEW public.uns_area_current_month IS 'compat shim — renamed to area_live_month 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_site_current_hour RENAME TO site_live_hour;
CREATE VIEW public.uns_site_current_hour WITH (security_invoker=true) AS SELECT * FROM public.site_live_hour;
COMMENT ON VIEW public.uns_site_current_hour IS 'compat shim — renamed to site_live_hour 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_site_current_day RENAME TO site_live_day;
CREATE VIEW public.uns_site_current_day WITH (security_invoker=true) AS SELECT * FROM public.site_live_day;
COMMENT ON VIEW public.uns_site_current_day IS 'compat shim — renamed to site_live_day 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_site_current_week RENAME TO site_live_week;
CREATE VIEW public.uns_site_current_week WITH (security_invoker=true) AS SELECT * FROM public.site_live_week;
COMMENT ON VIEW public.uns_site_current_week IS 'compat shim — renamed to site_live_week 2026-09-04 (uns->live cutover); drop in contract phase';
ALTER TABLE public.uns_site_current_month RENAME TO site_live_month;
CREATE VIEW public.uns_site_current_month WITH (security_invoker=true) AS SELECT * FROM public.site_live_month;
COMMENT ON VIEW public.uns_site_current_month IS 'compat shim — renamed to site_live_month 2026-09-04 (uns->live cutover); drop in contract phase';
COMMIT;
