-- rollback: recreate the 33 security_invoker compat shims
BEGIN;
CREATE OR REPLACE VIEW public.equipment_runtime_shift_1month WITH (security_invoker=true) AS SELECT * FROM public.equipment_oee_shift_monthly;
CREATE OR REPLACE VIEW public.uns_equipment_current_metrics WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_metrics;
CREATE OR REPLACE VIEW public.equipment_runtime_shift_1week WITH (security_invoker=true) AS SELECT * FROM public.equipment_oee_shift_weekly;
CREATE OR REPLACE VIEW public.uns_equipment_current_shift WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_shift;
CREATE OR REPLACE VIEW public.uns_equipment_current_month WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_month;
CREATE OR REPLACE VIEW public.uns_equipment_current_week WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_week;
CREATE OR REPLACE VIEW public.uns_equipment_current_hour WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_hour;
CREATE OR REPLACE VIEW public.uns_equipment_current_job WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_job;
CREATE OR REPLACE VIEW public.uns_equipment_current_day WITH (security_invoker=true) AS SELECT * FROM public.equipment_live_day;
CREATE OR REPLACE VIEW public.equipment_runtime_1month WITH (security_invoker=true) AS SELECT * FROM public.equipment_oee_monthly;
CREATE OR REPLACE VIEW public.equipment_runtime_shift WITH (security_invoker=true) AS SELECT * FROM public.equipment_oee_shift;
CREATE OR REPLACE VIEW public.equipment_runtime_1week WITH (security_invoker=true) AS SELECT * FROM public.equipment_oee_weekly;
CREATE OR REPLACE VIEW public.equipment_runtime_1hour WITH (security_invoker=true) AS SELECT * FROM public.equipment_oee_hourly;
CREATE OR REPLACE VIEW public.uns_site_current_month WITH (security_invoker=true) AS SELECT * FROM public.site_live_month;
CREATE OR REPLACE VIEW public.uns_area_current_shift WITH (security_invoker=true) AS SELECT * FROM public.area_live_shift;
CREATE OR REPLACE VIEW public.uns_area_current_month WITH (security_invoker=true) AS SELECT * FROM public.area_live_month;
CREATE OR REPLACE VIEW public.equipment_runtime_1day WITH (security_invoker=true) AS SELECT * FROM public.equipment_oee_daily;
CREATE OR REPLACE VIEW public.uns_site_current_week WITH (security_invoker=true) AS SELECT * FROM public.site_live_week;
CREATE OR REPLACE VIEW public.uns_site_current_hour WITH (security_invoker=true) AS SELECT * FROM public.site_live_hour;
CREATE OR REPLACE VIEW public.uns_area_current_week WITH (security_invoker=true) AS SELECT * FROM public.area_live_week;
CREATE OR REPLACE VIEW public.uns_area_current_hour WITH (security_invoker=true) AS SELECT * FROM public.area_live_hour;
CREATE OR REPLACE VIEW public.uns_site_current_day WITH (security_invoker=true) AS SELECT * FROM public.site_live_day;
CREATE OR REPLACE VIEW public.uns_area_current_day WITH (security_invoker=true) AS SELECT * FROM public.area_live_day;
CREATE OR REPLACE VIEW public.site_runtime_1month WITH (security_invoker=true) AS SELECT * FROM public.site_oee_monthly;
CREATE OR REPLACE VIEW public.area_runtime_1month WITH (security_invoker=true) AS SELECT * FROM public.area_oee_monthly;
CREATE OR REPLACE VIEW public.site_runtime_shift WITH (security_invoker=true) AS SELECT * FROM public.site_oee_shift;
CREATE OR REPLACE VIEW public.site_runtime_1week WITH (security_invoker=true) AS SELECT * FROM public.site_oee_weekly;
CREATE OR REPLACE VIEW public.site_runtime_1hour WITH (security_invoker=true) AS SELECT * FROM public.site_oee_hourly;
CREATE OR REPLACE VIEW public.area_runtime_shift WITH (security_invoker=true) AS SELECT * FROM public.area_oee_shift;
CREATE OR REPLACE VIEW public.area_runtime_1week WITH (security_invoker=true) AS SELECT * FROM public.area_oee_weekly;
CREATE OR REPLACE VIEW public.area_runtime_1hour WITH (security_invoker=true) AS SELECT * FROM public.area_oee_hourly;
CREATE OR REPLACE VIEW public.site_runtime_1day WITH (security_invoker=true) AS SELECT * FROM public.site_oee_daily;
CREATE OR REPLACE VIEW public.area_runtime_1day WITH (security_invoker=true) AS SELECT * FROM public.area_oee_daily;
COMMIT;
