package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/packiot/packiot-stack-alpha/services/analytics-sync/internal/replay"
)

// OrderChangedPayload — user_logs.category='order-changed'. Combined
// action that closes the OLD PO and optionally creates a NEW one in
// one atomic operator step.
//
// Real sampled payload (2026-07-01 staging):
//
//	{"idArea":3,"idSite":3,"idOrder":1782926737,"stopType":"finish",
//	 "timestamp":"...","idEquipment":5,"idEnterprise":2,
//	 "shouldCreatePo":true,"shouldOpenNewPo":true,
//	 "idProductionOrder":null,"oldIdProductionOrder":17465,
//	 "productionOrderQuantity":4206,"oldProductionOrderProdFinal":0}
//
// Note: idProductionOrder is NULL in the payload — the NEW PO's id
// is generated by edge-api at write time. shadow-mirror can't
// deterministically reproduce that id, so:
//   - Step 1 (always): UPDATE the old PO by its natural key
//     (id_enterprise, id_order), resolved from Flow 1 via
//     oldIdProductionOrder (bug 248 — surrogate ids diverge per flow,
//     so id_production_order lookups never match on shadow)
//   - Step 2 (if shouldCreatePo=true): INSERT a new PO with
//     ON CONFLICT (id_enterprise, id_order) DO NOTHING — the qualified
//     target keeps replays idempotent while letting any other
//     constraint violation surface as a dispatch failure (bug 247)
type OrderChangedPayload struct {
	IDArea                      int    `json:"idArea"`
	IDSite                      int    `json:"idSite"`
	IDOrder                     int64  `json:"idOrder"`
	StopType                    string `json:"stopType"`  // "finish" | "pause"
	Timestamp                   string `json:"timestamp"` // ISO-8601 UTC
	IDEquipment                 int    `json:"idEquipment"`
	IDEnterprise                int    `json:"idEnterprise"`
	ShouldCreatePo              bool   `json:"shouldCreatePo"`
	ShouldOpenNewPo             bool   `json:"shouldOpenNewPo"`
	OldIDProductionOrder        int64  `json:"oldIdProductionOrder"`
	ProductionOrderQuantity     int64  `json:"productionOrderQuantity"`
	OldProductionOrderProdFinal int64  `json:"oldProductionOrderProdFinal"`
}

// OrderChanged closes the old PO and (optionally) inserts a new one.
// Both operations replay against each shadow path.
func OrderChanged(logger *slog.Logger) replay.Handler {
	return func(ctx context.Context, mainPool, analyticsPool *pgxpool.Pool, u *replay.UserLog) error {
		var p OrderChangedPayload
		if err := json.Unmarshal(u.Payload, &p); err != nil {
			return replay.ErrSkip
		}
		if p.OldIDProductionOrder == 0 {
			return replay.ErrSkip
		}
		ts, err := time.Parse(time.RFC3339Nano, p.Timestamp)
		if err != nil {
			return replay.ErrSkip
		}
		oldKey, found, err := resolvePOKey(ctx, mainPool, p.OldIDProductionOrder)
		if err != nil {
			return fmt.Errorf("resolve old PO natural key: %w", err)
		}
		if !found {
			logger.Warn("order-changed: old Flow 1 PO not found",
				slog.Int64("id_user_log", u.ID),
				slog.Int64("old_id_production_order", p.OldIDProductionOrder))
			return replay.ErrSkip
		}
		if err := orderChangedOnSchema(ctx, mainPool, "shadow_go_port", &p, oldKey, ts, u.ID, logger); err != nil {
			return fmt.Errorf("shadow_go_port: %w", err)
		}
		if analyticsPool != nil {
			if err := orderChangedOnSchema(ctx, analyticsPool, "public", &p, oldKey, ts, u.ID, logger); err != nil {
				return fmt.Errorf("packiot_analytics: %w", err)
			}
		}
		return nil
	}
}

const sqlClosePOChanged = `UPDATE %s.production_orders
	   SET status = $1, ts_end = $2, production_final = $3, recalc_needed = true, last_update = now()
	 WHERE id_enterprise = $4 AND id_order = $5`

const sqlInsertPOChanged = `INSERT INTO %s.production_orders (
		id_enterprise, id_site, id_area, id_equipment, id_order,
		production_programmed, production_ordered, status, ts_start
	) VALUES ($1,$2,$3,$4,$5,$6,$6,2,$7)
	ON CONFLICT (id_enterprise, id_order) DO NOTHING`

// orderChangedOnSchema applies both the close-old and (optionally)
// create-new steps against a single pool+schema.
func orderChangedOnSchema(ctx context.Context, pool *pgxpool.Pool, schema string, p *OrderChangedPayload, oldKey poKey, ts time.Time, userLogID int64, logger *slog.Logger) error {
	// Step 1: close old PO
	status := 3 // finish
	if p.StopType == "pause" {
		status = 4
	}
	closeSQL := fmt.Sprintf(sqlClosePOChanged, schema)
	if err := execExpectingRows(ctx, pool, schema, "production_orders", userLogID, logger,
		closeSQL, status, ts, p.OldProductionOrderProdFinal, oldKey.IDEnterprise, oldKey.IDOrder); err != nil {
		return fmt.Errorf("close old PO: %w", err)
	}

	// Step 2 (optional): insert new PO
	if !p.ShouldCreatePo || p.IDOrder == 0 {
		return nil
	}
	// production_programmed + production_ordered both NOT NULL on prod.
	insertSQL := fmt.Sprintf(sqlInsertPOChanged, schema)
	_, err := pool.Exec(ctx, insertSQL,
		p.IDEnterprise, p.IDSite, p.IDArea, p.IDEquipment, p.IDOrder,
		p.ProductionOrderQuantity, ts,
	)
	return failOpenIfMissing(err, "production_orders", schema, userLogID, logger)
}
