-- t278b: COMMENT documentation for the gold schema of packiot_analytics (staging).
-- OEE = Availability (oee_a) x Performance (oee_p) x Quality (oee_q); all factors clamped to [0,1].
-- Grounded in stream-engine internal/rollup/*.go + pocontrol + barcode-service. Idempotent; non-destructive.

COMMENT ON TABLE gold.equipment_oee_hourly IS 'Gold OEE grain: one row per (id_equipment, hour). Foundation grain of the rollup cascade, computed by stream-engine internal/rollup/hour.go (runtime-rollup-hour). Exists only for lines/sectors (tp_equipment > 1); tp=1 machines are rolled up at shift/day, never hourly. gross/net/speed from the 1h categorical cagg (phase V); time-in-state + Availability/Quality from equipment_events overlaps (phase E); ideal_speed from the 1min tier LOCF. Composite oee and oee_a/oee_p/oee_q are clamped to [0,1] and satisfy oee = oee_a*oee_p*oee_q (CHECK *_oee_bounds).';
COMMENT ON COLUMN gold.equipment_oee_hourly.id_equipment IS 'FK -> equipments. The equipment (line/sector/machine) this grain row belongs to.';
COMMENT ON COLUMN gold.equipment_oee_hourly.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.equipment_oee_hourly.oee IS 'Composite OEE ratio in [0,1] (CHECK oee_bounds); = oee_a*oee_p*oee_q. NULL for tp=1 machines of LINE-metered enterprises (unmetered.go: ''not metered'' rather than a misleading 0). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_hourly.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.equipment_oee_hourly.oee_p IS 'Performance factor, ratio in [0,1] (CHECK oee_bounds). Throughput vs ideal speed; back-solved as oee/(oee_a*oee_q) or, under the canonical reconcile, gross*available/(ideal_production*running). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_hourly.oee_a IS 'Availability factor, ratio in [0,1] (CHECK oee_bounds). = running_time / scheduled-production-time (available window). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_hourly.oee_q IS 'Quality factor, ratio in [0,1] (CHECK oee_bounds). = net / gross (good units over produced units). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_hourly.available_time IS 'Scheduled production time in SECONDS = bucket wall-clock span - planned_downtime (LEAST-guarded >= 0). Denominator of Availability.';
COMMENT ON COLUMN gold.equipment_oee_hourly.running_time IS 'Time in the RUNNING state (equipment_events status=6) in SECONDS, capped at the bucket span (LEAST) so overlapping line/member events cannot exceed elapsed wall-clock.';
COMMENT ON COLUMN gold.equipment_oee_hourly.stopped_time IS 'Time in STOPPED states (equipment_events status IN (5,10,11)) in SECONDS.';
COMMENT ON COLUMN gold.equipment_oee_hourly.planned_downtime IS 'Time in PLANNED-downtime events in SECONDS (capped at the bucket span). Subtracted from wall-clock to yield available_time.';
COMMENT ON COLUMN gold.equipment_oee_hourly.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.equipment_oee_hourly.idle_time IS 'Idle time in SECONDS. Summed up the grain cascade but NOT populated by any base-grain writer in the new-stack stream-engine (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_hourly.idle_starved IS 'Starvation idle (no infeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_hourly.idle_blocked IS 'Blocking idle (no outfeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_hourly.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.equipment_oee_hourly.gross IS 'Gross produced count for the bucket = SUM(gross_production_incr) from the categorical cagg. COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_hourly.net IS 'Good (net) produced count for the bucket = SUM(net_production_incr). COUNT units. net <= gross.';
COMMENT ON COLUMN gold.equipment_oee_hourly.downtime IS 'Time in ANY non-running state (equipment_events status <> 6) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.equipment_oee_hourly.changeover_time IS 'Time in CHANGEOVER events (change_over=true) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.equipment_oee_hourly.scrap IS 'Rejected/scrap count = gross - net (COALESCE 0). COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_hourly.speed IS 'Average production speed over the bucket in COUNT-per-minute (avg of sum_speed/cnt_speed; shift grain averages state=6 buckets only).';
COMMENT ON COLUMN gold.equipment_oee_hourly.ts_value_production IS 'Production-day DATE this bucket belongs to (shift day anchor via piot_get_day_begin_by_*). Used to key the shift value/target passes.';
COMMENT ON COLUMN gold.equipment_oee_hourly.target_customized IS 'If true, target / proportional_target were set manually and the rollup will NOT overwrite them.';
COMMENT ON COLUMN gold.equipment_oee_hourly.proportional_target IS 'Elapsed-prorated production target in COUNT units for the (live) bucket. Hour = vl_day/24; shift = vl_day * (elapsed scheduled-productive time)/86400 so a live shift scales with elapsed and a completed shift settles at the full target. 0 / not overwritten when target_customized.';
COMMENT ON COLUMN gold.equipment_oee_hourly.id_team IS 'FK -> team assigned to this shift bucket (seeded from the shift calendar). Not written by the rollup metric passes.';
COMMENT ON COLUMN gold.equipment_oee_hourly.ideal_speed IS 'Ideal production speed in COUNT-per-minute, LOCF''d from PLC param 30701 (falls back to equipments.production_speed). Basis for ideal_production. 0 when unknown.';
COMMENT ON COLUMN gold.equipment_oee_hourly.computed_at IS 'Wall-clock time the rollup last WROTE this row (ADR-0036 5A lineage stamp). Distinct from source_watermark.';
COMMENT ON COLUMN gold.equipment_oee_hourly.source_watermark IS 'Latest event-time this row has visibility through = LEAST(bucket end, now()) (ADR-0036 5A). For a replayed old bucket, computed_at is recent while this settles at the bucket end.';

COMMENT ON TABLE gold.equipment_oee_shift IS 'Gold OEE grain: one row per (id_equipment, shift bucket). Computed by stream-engine internal/rollup/shift.go (runtime-rollup-shift). Covers tp>1 lines/sectors plus tp=1 machines of machine-level enterprises (UNION selector); line-metered tp=1 machines have their oee* NULLed by unmetered.go. Metric columns overwritten each tick; the shift-calendar columns (id_shift/id_shift_hour/id_team/duration/ts_range/ts_end/ts_value_production/target) are seeded by the DB provision procs. PK (id_equipment, ts_value); CHECK ts_value <= ts_end; CHECK oee_bounds [0,1].';
COMMENT ON COLUMN gold.equipment_oee_shift.id_runtime_shift IS 'Surrogate id; DEFAULT nextval from the legacy equipment_oee_shift_id_seq sequence (still live). Not the primary key -- the PK is (id_equipment, ts_value).';
COMMENT ON COLUMN gold.equipment_oee_shift.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.equipment_oee_shift.id_equipment IS 'FK -> equipments. The equipment (line/sector/machine) this grain row belongs to.';
COMMENT ON COLUMN gold.equipment_oee_shift.oee IS 'Composite OEE ratio in [0,1] (CHECK oee_bounds); = oee_a*oee_p*oee_q. NULL for tp=1 machines of line-metered enterprises (unmetered.go). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_shift.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.equipment_oee_shift.oee_p IS 'Performance factor, ratio in [0,1] (CHECK oee_bounds). Throughput vs ideal speed; back-solved as oee/(oee_a*oee_q) or, under the canonical reconcile, gross*available/(ideal_production*running). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_shift.oee_a IS 'Availability factor, ratio in [0,1] (CHECK oee_bounds). = running_time / scheduled-production-time (available window). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_shift.oee_q IS 'Quality factor, ratio in [0,1] (CHECK oee_bounds). = net / gross (good units over produced units). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_shift.available_time IS 'Scheduled production time in SECONDS = bucket wall-clock span - planned_downtime (LEAST-guarded >= 0). Denominator of Availability.';
COMMENT ON COLUMN gold.equipment_oee_shift.running_time IS 'Time in the RUNNING state (equipment_events status=6) in SECONDS, capped at the bucket span (LEAST) so overlapping line/member events cannot exceed elapsed wall-clock.';
COMMENT ON COLUMN gold.equipment_oee_shift.stopped_time IS 'Time in STOPPED states (equipment_events status IN (5,10,11)) in SECONDS.';
COMMENT ON COLUMN gold.equipment_oee_shift.planned_downtime IS 'Time in PLANNED-downtime events in SECONDS (capped at the bucket span). Subtracted from wall-clock to yield available_time.';
COMMENT ON COLUMN gold.equipment_oee_shift.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.equipment_oee_shift.idle_time IS 'Idle time in SECONDS. Summed up the grain cascade but NOT populated by any base-grain writer in the new-stack stream-engine (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_shift.idle_starved IS 'Starvation idle (no infeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_shift.idle_blocked IS 'Blocking idle (no outfeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_shift.id_shift IS 'FK -> shifts. The shift definition for this bucket (seeded from the shift calendar).';
COMMENT ON COLUMN gold.equipment_oee_shift.id_shift_hour IS 'FK -> shift_hours. The specific shift-calendar row (shift x weekday expansion) for this bucket.';
COMMENT ON COLUMN gold.equipment_oee_shift.id_team IS 'FK -> team assigned to this shift bucket (seeded from the shift calendar). Not written by the rollup metric passes.';
COMMENT ON COLUMN gold.equipment_oee_shift.duration IS 'Scheduled shift length (shift_size) in SECONDS, seeded from the shift calendar. Not the elapsed/running time.';
COMMENT ON COLUMN gold.equipment_oee_shift.ts_range IS 'tstzrange span [start, end) of the shift bucket (seeded from the shift calendar).';
COMMENT ON COLUMN gold.equipment_oee_shift.gross IS 'Gross produced count for the bucket = SUM(gross_production_incr) from the categorical cagg. COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_shift.net IS 'Good (net) produced count for the bucket = SUM(net_production_incr). COUNT units. net <= gross.';
COMMENT ON COLUMN gold.equipment_oee_shift.downtime IS 'Time in ANY non-running state (equipment_events status <> 6) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.equipment_oee_shift.changeover_time IS 'Time in CHANGEOVER events (change_over=true) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.equipment_oee_shift.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.equipment_oee_shift.ts_end IS 'End timestamp of the shift bucket. Upper bound used by the event-overlap phase; CHECK ts_value <= ts_end (on equipment_oee_shift).';
COMMENT ON COLUMN gold.equipment_oee_shift.manually_customized IS 'Legacy flag: row was manually edited (via edge-api/front4), not by the rollup. Default false; not written by the new-stack rollup.';
COMMENT ON COLUMN gold.equipment_oee_shift.invalidated IS 'Legacy flag: row marked invalid / excluded from reporting. Default false; not written by the new-stack rollup.';
COMMENT ON COLUMN gold.equipment_oee_shift.scrap IS 'Rejected/scrap count = gross - net (COALESCE 0). COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_shift.speed IS 'Average production speed over the bucket in COUNT-per-minute (avg of sum_speed/cnt_speed; shift grain averages state=6 buckets only).';
COMMENT ON COLUMN gold.equipment_oee_shift.cd_shift IS 'Denormalized shift code (shifts.cd_shift, e.g. ''MORNING'',''T1''); refreshed from the calendar by the shift value pass.';
COMMENT ON COLUMN gold.equipment_oee_shift.ts_value_production IS 'Production-day DATE this bucket belongs to (shift day anchor via piot_get_day_begin_by_*). Used to key the shift value/target passes.';
COMMENT ON COLUMN gold.equipment_oee_shift.target_customized IS 'If true, target / proportional_target were set manually and the rollup will NOT overwrite them.';
COMMENT ON COLUMN gold.equipment_oee_shift.proportional_target IS 'Elapsed-prorated production target in COUNT units for the (live) bucket. Hour = vl_day/24; shift = vl_day * (elapsed scheduled-productive time)/86400 so a live shift scales with elapsed and a completed shift settles at the full target. 0 / not overwritten when target_customized.';
COMMENT ON COLUMN gold.equipment_oee_shift.ideal_speed IS 'Ideal production speed in COUNT-per-minute, LOCF''d from PLC param 30701 (falls back to equipments.production_speed). Basis for ideal_production. 0 when unknown.';
COMMENT ON COLUMN gold.equipment_oee_shift.computed_at IS 'Wall-clock time the rollup last WROTE this row (ADR-0036 5A lineage stamp). Distinct from source_watermark.';
COMMENT ON COLUMN gold.equipment_oee_shift.source_watermark IS 'Latest event-time this row has visibility through = LEAST(bucket end, now()) (ADR-0036 5A). For a replayed old bucket, computed_at is recent while this settles at the bucket end.';

COMMENT ON TABLE gold.equipment_oee_daily IS 'Gold OEE grain: one row per (id_equipment, production day). Flagged recalc_needed by the hour cascade (hour.go hourCascadeDaySQL) and rolled up from the underlying grain. Feeds the weekly/monthly cascade (grains.go) and the area/site day rollup (entity_grains.go). oee* clamped to [0,1] (CHECK oee_bounds).';
COMMENT ON COLUMN gold.equipment_oee_daily.id_equipment IS 'FK -> equipments. The equipment (line/sector/machine) this grain row belongs to.';
COMMENT ON COLUMN gold.equipment_oee_daily.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.equipment_oee_daily.oee IS 'Composite OEE ratio in [0,1] (CHECK oee_bounds). Equals oee_a * oee_p * oee_q (net / ideal_production headline reconciled to the A*P*Q identity). Clamped: raw >1 collapses to 1, <0 to 0.';
COMMENT ON COLUMN gold.equipment_oee_daily.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.equipment_oee_daily.oee_p IS 'Performance factor, ratio in [0,1] (CHECK oee_bounds). Throughput vs ideal speed; back-solved as oee/(oee_a*oee_q) or, under the canonical reconcile, gross*available/(ideal_production*running). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_daily.oee_a IS 'Availability factor, ratio in [0,1] (CHECK oee_bounds). = running_time / scheduled-production-time (available window). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_daily.oee_q IS 'Quality factor, ratio in [0,1] (CHECK oee_bounds). = net / gross (good units over produced units). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_daily.available_time IS 'Scheduled production time in SECONDS = bucket wall-clock span - planned_downtime (LEAST-guarded >= 0). Denominator of Availability.';
COMMENT ON COLUMN gold.equipment_oee_daily.running_time IS 'Time in the RUNNING state (equipment_events status=6) in SECONDS, capped at the bucket span (LEAST) so overlapping line/member events cannot exceed elapsed wall-clock.';
COMMENT ON COLUMN gold.equipment_oee_daily.stopped_time IS 'Time in STOPPED states (equipment_events status IN (5,10,11)) in SECONDS.';
COMMENT ON COLUMN gold.equipment_oee_daily.planned_downtime IS 'Time in PLANNED-downtime events in SECONDS (capped at the bucket span). Subtracted from wall-clock to yield available_time.';
COMMENT ON COLUMN gold.equipment_oee_daily.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.equipment_oee_daily.idle_time IS 'Idle time in SECONDS. Summed up the grain cascade but NOT populated by any base-grain writer in the new-stack stream-engine (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_daily.idle_starved IS 'Starvation idle (no infeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_daily.idle_blocked IS 'Blocking idle (no outfeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_daily.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.equipment_oee_daily.gross IS 'Gross produced count for the bucket = SUM(gross_production_incr) from the categorical cagg. COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_daily.net IS 'Good (net) produced count for the bucket = SUM(net_production_incr). COUNT units. net <= gross.';
COMMENT ON COLUMN gold.equipment_oee_daily.downtime IS 'Time in ANY non-running state (equipment_events status <> 6) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.equipment_oee_daily.changeover_time IS 'Time in CHANGEOVER events (change_over=true) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.equipment_oee_daily.scrap IS 'Rejected/scrap count = gross - net (COALESCE 0). COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_daily.speed IS 'Average production speed over the bucket in COUNT-per-minute (avg of sum_speed/cnt_speed; shift grain averages state=6 buckets only).';
COMMENT ON COLUMN gold.equipment_oee_daily.target_customized IS 'If true, target / proportional_target were set manually and the rollup will NOT overwrite them.';
COMMENT ON COLUMN gold.equipment_oee_daily.proportional_target IS 'Elapsed-prorated production target in COUNT units for the (live) bucket. Hour = vl_day/24; shift = vl_day * (elapsed scheduled-productive time)/86400 so a live shift scales with elapsed and a completed shift settles at the full target. 0 / not overwritten when target_customized.';
COMMENT ON COLUMN gold.equipment_oee_daily.computed_at IS 'Wall-clock time the rollup last WROTE this row (ADR-0036 5A lineage stamp). Distinct from source_watermark.';
COMMENT ON COLUMN gold.equipment_oee_daily.source_watermark IS 'Latest event-time this row has visibility through = LEAST(bucket end, now()) (ADR-0036 5A). For a replayed old bucket, computed_at is recent while this settles at the bucket end.';

COMMENT ON TABLE gold.equipment_oee_weekly IS 'Gold OEE grain: one row per (id_equipment, ISO week start date). Computed by stream-engine internal/rollup/grains.go by SUMMing equipment_oee_daily over date_trunc(''week'', day). Time/count columns are BIGINT (wider than the base grains) to hold week-scale sums. oee* clamped to [0,1] (CHECK oee_bounds); the canonical A*P*Q reconcile makes oee = oee_a*oee_p*oee_q. (Historic amber bug: prod''s week fn wrote oee_p to the MONTH table -- fixed here.)';
COMMENT ON COLUMN gold.equipment_oee_weekly.id_equipment IS 'FK -> equipments. The equipment (line/sector/machine) this grain row belongs to.';
COMMENT ON COLUMN gold.equipment_oee_weekly.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.equipment_oee_weekly.oee IS 'Composite OEE ratio in [0,1] (CHECK oee_bounds). Equals oee_a * oee_p * oee_q (net / ideal_production headline reconciled to the A*P*Q identity). Clamped: raw >1 collapses to 1, <0 to 0.';
COMMENT ON COLUMN gold.equipment_oee_weekly.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.equipment_oee_weekly.oee_p IS 'Performance factor, ratio in [0,1] (CHECK oee_bounds). Throughput vs ideal speed; back-solved as oee/(oee_a*oee_q) or, under the canonical reconcile, gross*available/(ideal_production*running). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_weekly.oee_a IS 'Availability factor, ratio in [0,1] (CHECK oee_bounds). = running_time / scheduled-production-time (available window). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_weekly.oee_q IS 'Quality factor, ratio in [0,1] (CHECK oee_bounds). = net / gross (good units over produced units). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_weekly.available_time IS 'Scheduled production time in SECONDS = SUM of daily available_time (BIGINT for week-scale sums).';
COMMENT ON COLUMN gold.equipment_oee_weekly.running_time IS 'Running-state time in SECONDS = SUM of daily running_time (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_weekly.stopped_time IS 'Stopped-state time in SECONDS = SUM of daily stopped_time (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_weekly.planned_downtime IS 'Planned-downtime time in SECONDS = SUM of daily planned_downtime (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_weekly.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.equipment_oee_weekly.idle_time IS 'Idle time in SECONDS = SUM of daily idle_time (BIGINT). No base-grain writer populates the daily source in the new stack (dormant / 0).';
COMMENT ON COLUMN gold.equipment_oee_weekly.idle_starved IS 'Starvation idle in SECONDS = SUM of daily idle_starved (BIGINT). Dormant / 0 in the new stack.';
COMMENT ON COLUMN gold.equipment_oee_weekly.idle_blocked IS 'Blocking idle in SECONDS = SUM of daily idle_blocked (BIGINT). Dormant / 0 in the new stack.';
COMMENT ON COLUMN gold.equipment_oee_weekly.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.equipment_oee_weekly.gross IS 'Gross produced count for the bucket = SUM(gross_production_incr) from the categorical cagg. COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_weekly.net IS 'Good (net) produced count for the bucket = SUM(net_production_incr). COUNT units. net <= gross.';
COMMENT ON COLUMN gold.equipment_oee_weekly.downtime IS 'Non-running time in SECONDS = SUM of daily downtime (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_weekly.changeover_time IS 'Changeover time in SECONDS = SUM of daily changeover_time (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_weekly.scrap IS 'Rejected/scrap count = gross - net (COALESCE 0). COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_weekly.speed IS 'Average production speed over the bucket in COUNT-per-minute (avg of sum_speed/cnt_speed; shift grain averages state=6 buckets only).';
COMMENT ON COLUMN gold.equipment_oee_weekly.proportional_target IS 'Elapsed-prorated production target in COUNT units for the (live) bucket. Hour = vl_day/24; shift = vl_day * (elapsed scheduled-productive time)/86400 so a live shift scales with elapsed and a completed shift settles at the full target. 0 / not overwritten when target_customized.';
COMMENT ON COLUMN gold.equipment_oee_weekly.target_customized IS 'If true, target / proportional_target were set manually and the rollup will NOT overwrite them.';
COMMENT ON COLUMN gold.equipment_oee_weekly.computed_at IS 'Wall-clock time the rollup last WROTE this row (ADR-0036 5A lineage stamp). Distinct from source_watermark.';
COMMENT ON COLUMN gold.equipment_oee_weekly.source_watermark IS 'Latest event-time this row has visibility through = LEAST(bucket end, now()) (ADR-0036 5A). For a replayed old bucket, computed_at is recent while this settles at the bucket end.';

COMMENT ON TABLE gold.equipment_oee_monthly IS 'Gold OEE grain: one row per (id_equipment, month start date). Computed by stream-engine internal/rollup/grains.go by SUMMing equipment_oee_daily over date_trunc(''month'', day). Time/count columns are BIGINT to hold month-scale sums. oee* clamped to [0,1] (CHECK oee_bounds).';
COMMENT ON COLUMN gold.equipment_oee_monthly.id_equipment IS 'FK -> equipments. The equipment (line/sector/machine) this grain row belongs to.';
COMMENT ON COLUMN gold.equipment_oee_monthly.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.equipment_oee_monthly.oee IS 'Composite OEE ratio in [0,1] (CHECK oee_bounds). Equals oee_a * oee_p * oee_q (net / ideal_production headline reconciled to the A*P*Q identity). Clamped: raw >1 collapses to 1, <0 to 0.';
COMMENT ON COLUMN gold.equipment_oee_monthly.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.equipment_oee_monthly.oee_p IS 'Performance factor, ratio in [0,1] (CHECK oee_bounds). Throughput vs ideal speed; back-solved as oee/(oee_a*oee_q) or, under the canonical reconcile, gross*available/(ideal_production*running). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_monthly.oee_a IS 'Availability factor, ratio in [0,1] (CHECK oee_bounds). = running_time / scheduled-production-time (available window). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_monthly.oee_q IS 'Quality factor, ratio in [0,1] (CHECK oee_bounds). = net / gross (good units over produced units). Clamped to [0,1].';
COMMENT ON COLUMN gold.equipment_oee_monthly.available_time IS 'Scheduled production time in SECONDS = SUM of daily available_time (BIGINT for month-scale sums).';
COMMENT ON COLUMN gold.equipment_oee_monthly.running_time IS 'Running-state time in SECONDS = SUM of daily running_time (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_monthly.stopped_time IS 'Stopped-state time in SECONDS = SUM of daily stopped_time (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_monthly.planned_downtime IS 'Planned-downtime time in SECONDS = SUM of daily planned_downtime (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_monthly.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.equipment_oee_monthly.idle_time IS 'Idle time in SECONDS = SUM of daily idle_time (BIGINT). Dormant / 0 in the new stack.';
COMMENT ON COLUMN gold.equipment_oee_monthly.idle_starved IS 'Starvation idle in SECONDS = SUM of daily idle_starved (BIGINT). Dormant / 0 in the new stack.';
COMMENT ON COLUMN gold.equipment_oee_monthly.idle_blocked IS 'Blocking idle in SECONDS = SUM of daily idle_blocked (BIGINT). Dormant / 0 in the new stack.';
COMMENT ON COLUMN gold.equipment_oee_monthly.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.equipment_oee_monthly.gross IS 'Gross produced count for the bucket = SUM(gross_production_incr) from the categorical cagg. COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_monthly.net IS 'Good (net) produced count for the bucket = SUM(net_production_incr). COUNT units. net <= gross.';
COMMENT ON COLUMN gold.equipment_oee_monthly.downtime IS 'Non-running time in SECONDS = SUM of daily downtime (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_monthly.changeover_time IS 'Changeover time in SECONDS = SUM of daily changeover_time (BIGINT).';
COMMENT ON COLUMN gold.equipment_oee_monthly.scrap IS 'Rejected/scrap count = gross - net (COALESCE 0). COUNT units.';
COMMENT ON COLUMN gold.equipment_oee_monthly.speed IS 'Average production speed over the bucket in COUNT-per-minute (avg of sum_speed/cnt_speed; shift grain averages state=6 buckets only).';
COMMENT ON COLUMN gold.equipment_oee_monthly.proportional_target IS 'Elapsed-prorated production target in COUNT units for the (live) bucket. Hour = vl_day/24; shift = vl_day * (elapsed scheduled-productive time)/86400 so a live shift scales with elapsed and a completed shift settles at the full target. 0 / not overwritten when target_customized.';
COMMENT ON COLUMN gold.equipment_oee_monthly.target_customized IS 'If true, target / proportional_target were set manually and the rollup will NOT overwrite them.';
COMMENT ON COLUMN gold.equipment_oee_monthly.computed_at IS 'Wall-clock time the rollup last WROTE this row (ADR-0036 5A lineage stamp). Distinct from source_watermark.';
COMMENT ON COLUMN gold.equipment_oee_monthly.source_watermark IS 'Latest event-time this row has visibility through = LEAST(bucket end, now()) (ADR-0036 5A). For a replayed old bucket, computed_at is recent while this settles at the bucket end.';

COMMENT ON TABLE gold.equipment_oee_shift_weekly IS 'Legacy reduced shift-by-week aggregate grain (one row per equipment x shift x week). Skeleton rows are seeded by the DB provision proc piot_create_equipment_oee_shift_weekly; the new-stack stream-engine does NOT compute its metric columns (no rollup value/event writer targets it) -- only unmetered.go NULLs oee* for line-metered tp=1 machines. Carries no gross/net/scrap/speed/computed_at columns. Treat metric columns as largely dormant on the new stack unless a legacy pg proc populates them.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.oee IS 'OEE ratio in [0,1] (CHECK oee_bounds). Legacy shift-by-week aggregate; NOT computed by the new-stack rollup (only NULLed for line-metered machines). Treat as dormant unless a legacy pg proc writes it.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.oee_p IS 'Performance ratio in [0,1]. Legacy aggregate col; not written by the new-stack rollup (dormant).';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.oee_a IS 'Availability ratio in [0,1]. Legacy aggregate col; not written by the new-stack rollup (dormant).';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.oee_q IS 'Quality ratio in [0,1]. Legacy aggregate col; not written by the new-stack rollup (dormant).';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.available_time IS 'Scheduled production time in SECONDS = bucket wall-clock span - planned_downtime (LEAST-guarded >= 0). Denominator of Availability.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.running_time IS 'Time in the RUNNING state (equipment_events status=6) in SECONDS, capped at the bucket span (LEAST) so overlapping line/member events cannot exceed elapsed wall-clock.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.stopped_time IS 'Time in STOPPED states (equipment_events status IN (5,10,11)) in SECONDS.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.planned_downtime IS 'Time in PLANNED-downtime events in SECONDS (capped at the bucket span). Subtracted from wall-clock to yield available_time.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.idle_time IS 'Idle time in SECONDS. Summed up the grain cascade but NOT populated by any base-grain writer in the new-stack stream-engine (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.idle_starved IS 'Starvation idle (no infeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.idle_blocked IS 'Blocking idle (no outfeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.id_equipment IS 'FK -> equipments. The equipment (line/sector/machine) this grain row belongs to.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.id_shift IS 'FK -> shifts. The shift definition for this bucket (seeded from the shift calendar).';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.id_shift_hour IS 'FK -> shift_hours. The specific shift-calendar row (shift x weekday expansion) for this bucket.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.id_team IS 'FK -> team assigned to this shift bucket (seeded from the shift calendar). Not written by the rollup metric passes.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.duration IS 'Scheduled shift length (shift_size) in SECONDS, seeded from the shift calendar. Not the elapsed/running time.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.equipment_oee_shift_weekly.target_customized IS 'If true, target / proportional_target were set manually and the rollup will NOT overwrite them.';

COMMENT ON TABLE gold.equipment_oee_shift_monthly IS 'Legacy reduced shift-by-month aggregate grain (one row per equipment x shift x month). Skeleton rows seeded by piot_create_equipment_oee_shift_monthly; the new-stack stream-engine does NOT compute its metric columns (only unmetered.go NULLs oee* for line-metered tp=1 machines). No gross/net/scrap/speed columns. Treat metric columns as largely dormant on the new stack.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.oee IS 'OEE ratio in [0,1] (CHECK oee_bounds). Legacy shift-by-month aggregate; NOT computed by the new-stack rollup (dormant).';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.oee_p IS 'Performance ratio in [0,1]. Legacy aggregate col; not written by the new-stack rollup (dormant).';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.oee_a IS 'Availability ratio in [0,1]. Legacy aggregate col; not written by the new-stack rollup (dormant).';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.oee_q IS 'Quality ratio in [0,1]. Legacy aggregate col; not written by the new-stack rollup (dormant).';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.available_time IS 'Scheduled production time in SECONDS = bucket wall-clock span - planned_downtime (LEAST-guarded >= 0). Denominator of Availability.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.running_time IS 'Time in the RUNNING state (equipment_events status=6) in SECONDS, capped at the bucket span (LEAST) so overlapping line/member events cannot exceed elapsed wall-clock.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.stopped_time IS 'Time in STOPPED states (equipment_events status IN (5,10,11)) in SECONDS.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.planned_downtime IS 'Time in PLANNED-downtime events in SECONDS (capped at the bucket span). Subtracted from wall-clock to yield available_time.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.idle_time IS 'Idle time in SECONDS. Summed up the grain cascade but NOT populated by any base-grain writer in the new-stack stream-engine (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.idle_starved IS 'Starvation idle (no infeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.idle_blocked IS 'Blocking idle (no outfeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.id_equipment IS 'FK -> equipments. The equipment (line/sector/machine) this grain row belongs to.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.id_shift IS 'FK -> shifts. The shift definition for this bucket (seeded from the shift calendar).';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.id_shift_hour IS 'FK -> shift_hours. The specific shift-calendar row (shift x weekday expansion) for this bucket.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.id_team IS 'FK -> team assigned to this shift bucket (seeded from the shift calendar). Not written by the rollup metric passes.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.duration IS 'Scheduled shift length (shift_size) in SECONDS, seeded from the shift calendar. Not the elapsed/running time.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.equipment_oee_shift_monthly.target_customized IS 'If true, target / proportional_target were set manually and the rollup will NOT overwrite them.';

COMMENT ON TABLE gold.area_oee_daily IS 'Gold OEE grain: one row per (id_area, production day). Computed by stream-engine internal/rollup/entity_grains.go by SUMMing the daily grain of the area''s LINES (equipment_oee_daily where tp_equipment = 3). Flag re-sourced from the equipment day grain (day-flag cascade; the retired area_oee_hourly no longer drives it). oee* clamped to [0,1].';
COMMENT ON COLUMN gold.area_oee_daily.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.area_oee_daily.id_area IS 'FK -> areas. The area this aggregate grain row belongs to.';
COMMENT ON COLUMN gold.area_oee_daily.oee IS 'Composite OEE ratio in [0,1] (CHECK oee_bounds). Equals oee_a * oee_p * oee_q (net / ideal_production headline reconciled to the A*P*Q identity). Clamped: raw >1 collapses to 1, <0 to 0.';
COMMENT ON COLUMN gold.area_oee_daily.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.area_oee_daily.oee_p IS 'Performance factor, ratio in [0,1] (CHECK oee_bounds). Throughput vs ideal speed; back-solved as oee/(oee_a*oee_q) or, under the canonical reconcile, gross*available/(ideal_production*running). Clamped to [0,1].';
COMMENT ON COLUMN gold.area_oee_daily.oee_a IS 'Availability factor, ratio in [0,1] (CHECK oee_bounds). = running_time / scheduled-production-time (available window). Clamped to [0,1].';
COMMENT ON COLUMN gold.area_oee_daily.oee_q IS 'Quality factor, ratio in [0,1] (CHECK oee_bounds). = net / gross (good units over produced units). Clamped to [0,1].';
COMMENT ON COLUMN gold.area_oee_daily.available_time IS 'Scheduled production time in SECONDS = bucket wall-clock span - planned_downtime (LEAST-guarded >= 0). Denominator of Availability.';
COMMENT ON COLUMN gold.area_oee_daily.running_time IS 'Time in the RUNNING state (equipment_events status=6) in SECONDS, capped at the bucket span (LEAST) so overlapping line/member events cannot exceed elapsed wall-clock.';
COMMENT ON COLUMN gold.area_oee_daily.stopped_time IS 'Time in STOPPED states (equipment_events status IN (5,10,11)) in SECONDS.';
COMMENT ON COLUMN gold.area_oee_daily.planned_downtime IS 'Time in PLANNED-downtime events in SECONDS (capped at the bucket span). Subtracted from wall-clock to yield available_time.';
COMMENT ON COLUMN gold.area_oee_daily.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.area_oee_daily.idle_time IS 'Idle time in SECONDS. Summed up the grain cascade but NOT populated by any base-grain writer in the new-stack stream-engine (dormant / 0 on staging).';
COMMENT ON COLUMN gold.area_oee_daily.idle_starved IS 'Starvation idle (no infeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.area_oee_daily.idle_blocked IS 'Blocking idle (no outfeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.area_oee_daily.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.area_oee_daily.gross IS 'Gross produced count for the bucket = SUM(gross_production_incr) from the categorical cagg. COUNT units.';
COMMENT ON COLUMN gold.area_oee_daily.net IS 'Good (net) produced count for the bucket = SUM(net_production_incr). COUNT units. net <= gross.';
COMMENT ON COLUMN gold.area_oee_daily.downtime IS 'Time in ANY non-running state (equipment_events status <> 6) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.area_oee_daily.changeover_time IS 'Time in CHANGEOVER events (change_over=true) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.area_oee_daily.scrap IS 'Rejected/scrap count = gross - net (COALESCE 0). COUNT units.';
COMMENT ON COLUMN gold.area_oee_daily.speed IS 'Average production speed over the bucket in COUNT-per-minute (avg of sum_speed/cnt_speed; shift grain averages state=6 buckets only).';
COMMENT ON COLUMN gold.area_oee_daily.proportional_target IS 'Elapsed-prorated production target in COUNT units for the (live) bucket. Hour = vl_day/24; shift = vl_day * (elapsed scheduled-productive time)/86400 so a live shift scales with elapsed and a completed shift settles at the full target. 0 / not overwritten when target_customized.';
COMMENT ON COLUMN gold.area_oee_daily.computed_at IS 'Wall-clock time the rollup last WROTE this row (ADR-0036 5A lineage stamp). Distinct from source_watermark.';
COMMENT ON COLUMN gold.area_oee_daily.source_watermark IS 'Latest event-time this row has visibility through = LEAST(bucket end, now()) (ADR-0036 5A). For a replayed old bucket, computed_at is recent while this settles at the bucket end.';

COMMENT ON TABLE gold.area_oee_shift IS 'Gold OEE grain: one row per (id_area, shift bucket). Computed by entity_grains.go by SUMMing equipment_oee_shift over the area''s equipment for the same ts_value. Flagged by shift.go''s area cascade. oee* clamped to [0,1].';
COMMENT ON COLUMN gold.area_oee_shift.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.area_oee_shift.id_area IS 'FK -> areas. The area this aggregate grain row belongs to.';
COMMENT ON COLUMN gold.area_oee_shift.oee IS 'Composite OEE ratio in [0,1] (CHECK oee_bounds). Equals oee_a * oee_p * oee_q (net / ideal_production headline reconciled to the A*P*Q identity). Clamped: raw >1 collapses to 1, <0 to 0.';
COMMENT ON COLUMN gold.area_oee_shift.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.area_oee_shift.oee_p IS 'Performance factor, ratio in [0,1] (CHECK oee_bounds). Throughput vs ideal speed; back-solved as oee/(oee_a*oee_q) or, under the canonical reconcile, gross*available/(ideal_production*running). Clamped to [0,1].';
COMMENT ON COLUMN gold.area_oee_shift.oee_a IS 'Availability factor, ratio in [0,1] (CHECK oee_bounds). = running_time / scheduled-production-time (available window). Clamped to [0,1].';
COMMENT ON COLUMN gold.area_oee_shift.oee_q IS 'Quality factor, ratio in [0,1] (CHECK oee_bounds). = net / gross (good units over produced units). Clamped to [0,1].';
COMMENT ON COLUMN gold.area_oee_shift.available_time IS 'Scheduled production time in SECONDS = bucket wall-clock span - planned_downtime (LEAST-guarded >= 0). Denominator of Availability.';
COMMENT ON COLUMN gold.area_oee_shift.running_time IS 'Time in the RUNNING state (equipment_events status=6) in SECONDS, capped at the bucket span (LEAST) so overlapping line/member events cannot exceed elapsed wall-clock.';
COMMENT ON COLUMN gold.area_oee_shift.stopped_time IS 'Time in STOPPED states (equipment_events status IN (5,10,11)) in SECONDS.';
COMMENT ON COLUMN gold.area_oee_shift.planned_downtime IS 'Time in PLANNED-downtime events in SECONDS (capped at the bucket span). Subtracted from wall-clock to yield available_time.';
COMMENT ON COLUMN gold.area_oee_shift.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.area_oee_shift.idle_time IS 'Idle time in SECONDS. Summed up the grain cascade but NOT populated by any base-grain writer in the new-stack stream-engine (dormant / 0 on staging).';
COMMENT ON COLUMN gold.area_oee_shift.idle_starved IS 'Starvation idle (no infeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.area_oee_shift.idle_blocked IS 'Blocking idle (no outfeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.area_oee_shift.id_shift IS 'FK -> shifts. The shift definition for this bucket (seeded from the shift calendar).';
COMMENT ON COLUMN gold.area_oee_shift.id_shift_hour IS 'FK -> shift_hours. The specific shift-calendar row (shift x weekday expansion) for this bucket.';
COMMENT ON COLUMN gold.area_oee_shift.id_team IS 'FK -> team assigned to this shift bucket (seeded from the shift calendar). Not written by the rollup metric passes.';
COMMENT ON COLUMN gold.area_oee_shift.duration IS 'Scheduled shift length (shift_size) in SECONDS, seeded from the shift calendar. Not the elapsed/running time.';
COMMENT ON COLUMN gold.area_oee_shift.ts_range IS 'tstzrange span [start, end) of the shift bucket (seeded from the shift calendar).';
COMMENT ON COLUMN gold.area_oee_shift.gross IS 'Gross produced count for the bucket = SUM(gross_production_incr) from the categorical cagg. COUNT units.';
COMMENT ON COLUMN gold.area_oee_shift.net IS 'Good (net) produced count for the bucket = SUM(net_production_incr). COUNT units. net <= gross.';
COMMENT ON COLUMN gold.area_oee_shift.downtime IS 'Time in ANY non-running state (equipment_events status <> 6) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.area_oee_shift.changeover_time IS 'Time in CHANGEOVER events (change_over=true) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.area_oee_shift.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.area_oee_shift.ts_end IS 'End timestamp of the shift bucket. Upper bound used by the event-overlap phase; CHECK ts_value <= ts_end (on equipment_oee_shift).';
COMMENT ON COLUMN gold.area_oee_shift.ts_value_production IS 'Production-day DATE this bucket belongs to (shift day anchor via piot_get_day_begin_by_*). Used to key the shift value/target passes.';
COMMENT ON COLUMN gold.area_oee_shift.target_customized IS 'If true, target / proportional_target were set manually and the rollup will NOT overwrite them.';
COMMENT ON COLUMN gold.area_oee_shift.proportional_target IS 'Elapsed-prorated production target in COUNT units for the (live) bucket. Hour = vl_day/24; shift = vl_day * (elapsed scheduled-productive time)/86400 so a live shift scales with elapsed and a completed shift settles at the full target. 0 / not overwritten when target_customized.';
COMMENT ON COLUMN gold.area_oee_shift.scrap IS 'Rejected/scrap count = gross - net (COALESCE 0). COUNT units.';
COMMENT ON COLUMN gold.area_oee_shift.computed_at IS 'Wall-clock time the rollup last WROTE this row (ADR-0036 5A lineage stamp). Distinct from source_watermark.';
COMMENT ON COLUMN gold.area_oee_shift.source_watermark IS 'Latest event-time this row has visibility through = LEAST(bucket end, now()) (ADR-0036 5A). For a replayed old bucket, computed_at is recent while this settles at the bucket end.';

COMMENT ON TABLE gold.site_oee_shift IS 'Gold OEE grain: one row per (id_site, shift bucket). Computed by entity_grains.go by SUMMing area_oee_shift over the site''s areas. NOTE: the sibling site DAY grain (site_oee_daily) was DROPPED in t273 (only consumer was current_rest.go->site_live_day, itself unread); site SHIFT stays because it feeds serving.oee_progress. oee* clamped to [0,1].';
COMMENT ON COLUMN gold.site_oee_shift.ts_value IS 'Bucket start / anchor timestamp for this grain row (part of the natural key).';
COMMENT ON COLUMN gold.site_oee_shift.id_site IS 'FK -> sites. The site this aggregate grain row belongs to.';
COMMENT ON COLUMN gold.site_oee_shift.oee IS 'Composite OEE ratio in [0,1] (CHECK oee_bounds). Equals oee_a * oee_p * oee_q (net / ideal_production headline reconciled to the A*P*Q identity). Clamped: raw >1 collapses to 1, <0 to 0.';
COMMENT ON COLUMN gold.site_oee_shift.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.site_oee_shift.oee_p IS 'Performance factor, ratio in [0,1] (CHECK oee_bounds). Throughput vs ideal speed; back-solved as oee/(oee_a*oee_q) or, under the canonical reconcile, gross*available/(ideal_production*running). Clamped to [0,1].';
COMMENT ON COLUMN gold.site_oee_shift.oee_a IS 'Availability factor, ratio in [0,1] (CHECK oee_bounds). = running_time / scheduled-production-time (available window). Clamped to [0,1].';
COMMENT ON COLUMN gold.site_oee_shift.oee_q IS 'Quality factor, ratio in [0,1] (CHECK oee_bounds). = net / gross (good units over produced units). Clamped to [0,1].';
COMMENT ON COLUMN gold.site_oee_shift.available_time IS 'Scheduled production time in SECONDS = bucket wall-clock span - planned_downtime (LEAST-guarded >= 0). Denominator of Availability.';
COMMENT ON COLUMN gold.site_oee_shift.running_time IS 'Time in the RUNNING state (equipment_events status=6) in SECONDS, capped at the bucket span (LEAST) so overlapping line/member events cannot exceed elapsed wall-clock.';
COMMENT ON COLUMN gold.site_oee_shift.stopped_time IS 'Time in STOPPED states (equipment_events status IN (5,10,11)) in SECONDS.';
COMMENT ON COLUMN gold.site_oee_shift.planned_downtime IS 'Time in PLANNED-downtime events in SECONDS (capped at the bucket span). Subtracted from wall-clock to yield available_time.';
COMMENT ON COLUMN gold.site_oee_shift.ideal_production IS 'Theoretical ideal-speed output over the available window, in COUNT units = (available_time/60) * ideal_speed. Denominator of Performance; a raw oee_p>1 means ideal_speed is set too low.';
COMMENT ON COLUMN gold.site_oee_shift.idle_time IS 'Idle time in SECONDS. Summed up the grain cascade but NOT populated by any base-grain writer in the new-stack stream-engine (dormant / 0 on staging).';
COMMENT ON COLUMN gold.site_oee_shift.idle_starved IS 'Starvation idle (no infeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.site_oee_shift.idle_blocked IS 'Blocking idle (no outfeed) in SECONDS. Summed up the cascade only; no base-grain writer in the new stack (dormant / 0 on staging).';
COMMENT ON COLUMN gold.site_oee_shift.id_shift IS 'FK -> shifts. The shift definition for this bucket (seeded from the shift calendar).';
COMMENT ON COLUMN gold.site_oee_shift.id_shift_hour IS 'FK -> shift_hours. The specific shift-calendar row (shift x weekday expansion) for this bucket.';
COMMENT ON COLUMN gold.site_oee_shift.id_team IS 'FK -> team assigned to this shift bucket (seeded from the shift calendar). Not written by the rollup metric passes.';
COMMENT ON COLUMN gold.site_oee_shift.duration IS 'Scheduled shift length (shift_size) in SECONDS, seeded from the shift calendar. Not the elapsed/running time.';
COMMENT ON COLUMN gold.site_oee_shift.ts_range IS 'tstzrange span [start, end) of the shift bucket (seeded from the shift calendar).';
COMMENT ON COLUMN gold.site_oee_shift.gross IS 'Gross produced count for the bucket = SUM(gross_production_incr) from the categorical cagg. COUNT units.';
COMMENT ON COLUMN gold.site_oee_shift.net IS 'Good (net) produced count for the bucket = SUM(net_production_incr). COUNT units. net <= gross.';
COMMENT ON COLUMN gold.site_oee_shift.downtime IS 'Time in ANY non-running state (equipment_events status <> 6) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.site_oee_shift.changeover_time IS 'Time in CHANGEOVER events (change_over=true) in SECONDS (capped at bucket span).';
COMMENT ON COLUMN gold.site_oee_shift.target IS 'Production target for the bucket, in COUNT units (from core.production_targets). 0 when no target; NOT overwritten while target_customized is true.';
COMMENT ON COLUMN gold.site_oee_shift.ts_end IS 'End timestamp of the shift bucket. Upper bound used by the event-overlap phase; CHECK ts_value <= ts_end (on equipment_oee_shift).';
COMMENT ON COLUMN gold.site_oee_shift.ts_value_production IS 'Production-day DATE this bucket belongs to (shift day anchor via piot_get_day_begin_by_*). Used to key the shift value/target passes.';
COMMENT ON COLUMN gold.site_oee_shift.target_customized IS 'If true, target / proportional_target were set manually and the rollup will NOT overwrite them.';
COMMENT ON COLUMN gold.site_oee_shift.proportional_target IS 'Elapsed-prorated production target in COUNT units for the (live) bucket. Hour = vl_day/24; shift = vl_day * (elapsed scheduled-productive time)/86400 so a live shift scales with elapsed and a completed shift settles at the full target. 0 / not overwritten when target_customized.';
COMMENT ON COLUMN gold.site_oee_shift.scrap IS 'Rejected/scrap count = gross - net (COALESCE 0). COUNT units.';
COMMENT ON COLUMN gold.site_oee_shift.computed_at IS 'Wall-clock time the rollup last WROTE this row (ADR-0036 5A lineage stamp). Distinct from source_watermark.';
COMMENT ON COLUMN gold.site_oee_shift.source_watermark IS 'Latest event-time this row has visibility through = LEAST(bucket end, now()) (ADR-0036 5A). For a replayed old bucket, computed_at is recent while this settles at the bucket end.';

COMMENT ON TABLE gold.production_orders_runtime IS 'Gold: one OEE/production row per production-order RUN on an equipment. Row created on PO start and closed (upper bound of runtime_timerange set) on PO stop by stream-engine internal/pocontrol/pocontrol.go. Metric columns filled by internal/rollup/compute.go (po-runtime-compute): gross_production/net_production/oee_q/speed from equipment_values, running_time/stopped_time from equipment_events overlaps. recalc.go READS this table (sums across runs) to write PO-level OEE back to core.production_orders. GiST EXCLUDE (id_equipment, runtime_timerange) forbids overlapping runs per equipment; CHECK oee_bounds [0,1].';
COMMENT ON COLUMN gold.production_orders_runtime.id_production_order IS 'FK -> production_orders. The production order this run row belongs to.';
COMMENT ON COLUMN gold.production_orders_runtime.runtime_timerange IS 'tstzrange of this PO run on the equipment; open upper bound = run still in progress (closed on PO stop). GiST EXCLUDE (id_equipment WITH =, runtime_timerange WITH &&) forbids overlapping runs per equipment.';
COMMENT ON COLUMN gold.production_orders_runtime.oee IS 'OEE ratio in [0,1] (CHECK oee_bounds). NOT written by the new-stack stream-engine (0 on staging); PO-level OEE is aggregated by recalc.go into core.production_orders instead.';
COMMENT ON COLUMN gold.production_orders_runtime.recalc_needed IS 'Dirty flag: true => this row will be recomputed on the next rollup tick. Cleared by the compute pass, re-set by the tail re-flag for recent/current buckets.';
COMMENT ON COLUMN gold.production_orders_runtime.oee_p IS 'Performance ratio in [0,1]. NOT written by the new-stack stream-engine on this table (0 on staging); see recalc.go -> core.production_orders.';
COMMENT ON COLUMN gold.production_orders_runtime.oee_a IS 'Availability ratio in [0,1]. NOT written by the new-stack stream-engine on this table (0 on staging); see recalc.go -> core.production_orders.';
COMMENT ON COLUMN gold.production_orders_runtime.oee_q IS 'Quality factor in [0,1] (CHECK oee_bounds) = net/gross; the ONLY OEE factor compute.go writes on this table. Clamped.';
COMMENT ON COLUMN gold.production_orders_runtime.available_time IS 'Scheduled production time in SECONDS. Legacy col READ by recalc.go but NOT written by the new-stack compute pass (0 on staging).';
COMMENT ON COLUMN gold.production_orders_runtime.running_time IS 'Running-state time in SECONDS (status=6 event overlaps, compute.go phase B), capped at the PO run wall-clock span.';
COMMENT ON COLUMN gold.production_orders_runtime.stopped_time IS 'Stopped-state time in SECONDS (status IN (5,10,11) event overlaps, compute.go phase B).';
COMMENT ON COLUMN gold.production_orders_runtime.planned_downtime IS 'Planned-downtime SECONDS. Legacy col READ by recalc.go but NOT written by the new-stack compute pass (0 on staging).';
COMMENT ON COLUMN gold.production_orders_runtime.ideal_production IS 'Ideal-speed output (COUNT). Legacy col; NOT written by the new-stack compute pass (0 on staging).';
COMMENT ON COLUMN gold.production_orders_runtime.idle_time IS 'Idle SECONDS. Legacy col; not written by the new-stack compute pass (0 on staging).';
COMMENT ON COLUMN gold.production_orders_runtime.idle_starved IS 'Starvation idle SECONDS. Legacy col; not written by the new-stack compute pass (0 on staging).';
COMMENT ON COLUMN gold.production_orders_runtime.idle_blocked IS 'Blocking idle SECONDS. Legacy col; not written by the new-stack compute pass (0 on staging).';
COMMENT ON COLUMN gold.production_orders_runtime.id_production_orders_runtime IS 'Legacy duplicate surrogate id (plural spelling), populated alongside the PK id_production_order_runtime. UNCERTAIN: appears to be a pre-rename leftover kept for legacy consumers; both columns hold values on staging.';
COMMENT ON COLUMN gold.production_orders_runtime.id_equipment IS 'FK -> equipments. The equipment this PO run executed on.';
COMMENT ON COLUMN gold.production_orders_runtime.id_production_order_runtime IS 'BIGINT surrogate PRIMARY KEY of this run row.';
COMMENT ON COLUMN gold.production_orders_runtime.net_production IS 'Good (net) produced count for the run (double precision) = SUM(net_production_incr) (compute.go phase A).';
COMMENT ON COLUMN gold.production_orders_runtime.gross_production IS 'Gross produced count for the run (double precision) = SUM(gross_production_incr) from equipment_values (compute.go phase A).';
COMMENT ON COLUMN gold.production_orders_runtime.downtime IS 'Non-running SECONDS. Legacy col; NOT written by the new-stack compute pass (0 on staging).';
COMMENT ON COLUMN gold.production_orders_runtime.changeover_time IS 'Changeover SECONDS. Legacy col; NOT written by the new-stack compute pass (0 on staging).';
COMMENT ON COLUMN gold.production_orders_runtime.speed IS 'Average production speed over the run in COUNT-per-minute (avg equipment_values.speed, compute.go phase A).';
COMMENT ON COLUMN gold.production_orders_runtime.last_update IS 'Timestamp of the last recalc write (DEFAULT CURRENT_TIMESTAMP; set to now() by recalc.go).';
COMMENT ON COLUMN gold.production_orders_runtime.multiplier IS 'Legacy count multiplier (double precision). UNCERTAIN: unused on the new stack -- NULL for all rows on staging.';

COMMENT ON TABLE gold.po_box_counter IS 'Gold: per-production-order gapless box counter, the advisory-lock anchor for barcode label assignment. One row per PO. Written by services/barcode-service (scans.go) under pg_advisory_xact_lock(id_production_order): reads last_label_seq, assigns next = last+1, UPSERTs. This is the fast lock-anchored copy; the authoritative recomputable totals live in the v_po_box_totals view over box_scans.';
COMMENT ON COLUMN gold.po_box_counter.id_production_order IS 'PRIMARY KEY, FK -> production_orders. The PO this counter tracks.';
COMMENT ON COLUMN gold.po_box_counter.id_enterprise IS 'FK -> enterprises. Tenant owning the PO (denormalized for tenant-scoped reads).';
COMMENT ON COLUMN gold.po_box_counter.last_label_seq IS 'Gapless per-PO label sequence high-water mark (BIGINT). Read under pg_advisory_xact_lock(id_production_order); next label = last_label_seq + 1. Upserted as GREATEST(existing, new).';
COMMENT ON COLUMN gold.po_box_counter.total_qty IS 'Running SUM of box quantities that count toward the total (counts_toward_total scans), BIGINT. Upserted as existing + delta. Authoritative recomputable total lives in v_po_box_totals.';
COMMENT ON COLUMN gold.po_box_counter.updated_at IS 'Timestamp of the last upsert (set to now() on each scan).';

